"""Generate church UI localisation and fallback strings; no claim of translated fallback text."""
from pathlib import Path
import json,argparse,re
ROOT=Path(__file__).resolve().parents[1]
DATA={
  "rip_church_close": "Close",
  "rip_church.2.t": "Moscow and the Third Rome",
  "rip_church.2.d": "Writers at the Muscovite court describe Moscow as a guardian of the Orthodox inheritance. This sixteenth-century political theology does not itself create a new creed or end communion with the eastern patriarchates. Universal jurisdiction would require a separate, deliberate claim.",
  "rip_church.2.a": "Cultivate the Third Rome ideal",
  "rip_church.2.b": "Emphasize our place among the Orthodox churches",
  "rip_church.3.t": "A Recognized Patriarchate",
  "rip_church.3.d": "The ecclesiastical settlement recognizes our patriarchate within the wider Orthodox communion. Moscow accepts its place after the four ancient eastern patriarchates. Our centralized church remains a distinct political institution; recognition does not abolish its internal responsibilities.",
  "rip_church.5.t": "The Florentine Settlement Endures",
  "rip_church.5.d": "Our negotiated settlement has sustained a union that historically failed to gain lasting general acceptance. This is an alternative historical path: the Byzantine rite and its bishops remain, while communion with Rome is accepted. Parish integration will proceed locally.",
  "rip_church.6.t": "The Institutions of Communion",
  "rip_church.6.d": "Only one ten-year privilege may operate at a time. Eastern institutions draw on internal church authority; Roman support draws on Papal Standing. All options cost money. The position of Communion Balance determines which instruments are available.",
  "rip_church_recognition_refuse": "Claim an independent universal church — alternative history",
  "rip_church_nodes.1.t": "Fund the Missionary Network",
  "rip_church_nodes.1.d": "Register an eligible node, then select Missionary Network in its native merchant policies. Registration prepays 2 Fervor and reserves 2 Fervor each month until closed, even if a different trade policy is selected. Each node needs a merchant, 50% trade power, a controlled core parish with a temple connected to the capital's Muscovite church, and neighbouring missionary targets. One node is allowed; the schismatic branch allows two.",
  "rip_church_mission_network": "Missionary Network",
  "rip_church_mission_network_desc": "A funded network of monasteries, traders and frontier parishes. Requires a registered node, merchant, 50% trade power, connected controlled church infrastructure and an active Apostolic Mission. Conversion is gradual.",
  "rip_church_ro_heading": "THE MUSCOVITE CHURCH\\n[Root.GetChurchROStatus]",
  "rip_church_ro_resources": "Authority band: [Root.rip_church_pa_display.GetValue]%\\nIcons: [Root.rip_church_icons.GetValue] / [Root.rip_church_capacity.GetValue]   Fervor: [Root.rip_church_fervor.GetValue] / 100\\nMonthly fuel: +[Root.rip_church_fervor_income.GetValue] / -[Root.rip_church_fervor_cost.GetValue]   Missions: [Root.rip_church_nodes.GetValue]",
  "rip_church_ro_help": "Authority supplies capacity; Fervor pays for active policies. Activation: 10 Fervor. Upkeep for 1/2/3/4 icons: 2/4/8/14 monthly, plus 2 per funded node. The newest icon closes first if capacity or fuel runs out.",
  "rip_church_gc_heading": "THE UNION OF THE CHURCHES\\n[Root.GetChurchGCOrientation]",
  "rip_church_gc_resources": "Communion Balance: [Root.rip_church_communion.GetValue] (-100 East / +100 Rome)\\nAuthority band: [Root.rip_church_pa_display.GetValue]%\\nPapal Standing: [Root.rip_church_papal_standing.GetValue] / 100\\nMonthly Standing: +[Root.rip_church_standing_income.GetValue]",
  "rip_church_gc_help": "Authority belongs to the Eastern hierarchy. Papal Standing pays for limited Roman support. Shift policy by 20 for 25 ADM, once in five years. Recognize local rites from an owned province's panel; concessions protect stability but reduce direct taxation and recruitment.",
  "rip_church_gc_privilege_state": "Active settlement: [Root.GetChurchPrivilege]",
  "rip_church_east_button": "Toward the East",
  "rip_church_rome_button": "Toward Rome",
  "rip_church_nodes_button": "Missionary networks",
  "rip_church_reconcile_button": "Negotiate reconciliation",
  "rip_church_privileges_button": "Church privileges",
  "rip_church_center_button": "Found the Union's seat",
  "rip_church_ecumenism_button": "Conclude ecumenical settlement",
  "rip_church_gc_infrastructure_button": "Eastern infrastructure",
  "rip_church_gc_coexistence_button": "Agreement of coexistence",
  "rip_church_gc_legate_button": "Request a papal legate",
  "rip_church_gc_papal_support_button": "Request dynastic / moral support",
  "rip_church_rite_heading": "CONFESSIONAL AUTONOMY",
  "rip_church_rite_state": "[Root.GetChurchRiteStatus]",
  "rip_church_rite_help": "Recognizing a rite costs 1 ADM per current development. It excludes the parish from religious disunity, reduces unrest by 2, and reduces tax by 15% and manpower by 20%. The agreement lasts at least ten years. Revocation causes unrest for ten years.",
  "rip_church_recognize_rite_button": "Recognize the local rite",
  "rip_church_revoke_rite_button": "Revoke confessional autonomy",
  "rip_church_latin_consent_button": "Consent to Byzantine integration",
  "rip_church_rite_affordable_tt": "Our treasury of administrative power covers 1 ADM per development of this province.",
  "rip_church_ro_unrecognized": "Unrecognized autocephaly",
  "rip_church_ro_provisional": "Patriarchate recognized; conciliar confirmation pending",
  "rip_church_ro_recognized": "Recognized patriarchate within Orthodox communion",
  "rip_church_ro_schismatic": "Independent Third Rome church — alternative history",
  "rip_church_ro_reconciling": "Reconciliation under negotiation",
  "rip_church_gc_east": "Eastern autonomy",
  "rip_church_gc_middle": "Balanced communion",
  "rip_church_gc_rome": "Roman integration",
  "rip_church_active": "ACTIVE",
  "rip_church_inactive": "Inactive",
  "rip_church_none": "None",
  "rip_church_rite_recognized": "The local rite has a binding agreement of confessional autonomy.",
  "rip_church_rite_unrecognized": "The local rite has no agreement of confessional autonomy.",
  "rip_church_rite_consent": "The Latin parish has consented to gradual Byzantine integration.",
  "rip_church_nodes_button_tt": "Register or close missionary networks. Registration prepays 2 Fervor; each registered node reserves 2 per month. Choose the native Missionary Network trade policy after funding.",
  "rip_church_reconcile_button_tt": "Costs 100 DIP and 20 Authority. Negotiations last at least five years and conclude at peace with stability 1. Universal claims are renounced; internal discontent lasts ten years.",
  "rip_church_east_button_tt": "Costs 25 ADM; move 20 toward Eastern autonomy. Five-year policy interval. Existing contracts keep their original expiry.",
  "rip_church_rome_button_tt": "Costs 25 ADM; move 20 toward Roman integration. Five-year policy interval. Existing contracts keep their original expiry.",
  "rip_church_center_button_tt": "Only one centre exists worldwide. Costs 100 ADM and one year's income. Requires peace, stability 1, and a controlled Greek Catholic core with 10 development and a temple or cathedral. Twenty years between foundations.",
  "rip_church_privileges_button_tt": "Choose one ten-year church privilege. Eastern options require 20 Authority; Roman options require 30 Papal Standing and good relations with PAP. Standard price: 100 ducats; Eastern infrastructure costs 75 under Eastern orientation.",
  "rip_church_ecumenism_button_tt": "Twenty years of union, ten years of balanced policy without forced conversion, stability 2, 60 Papal Standing, recognized Orthodox and Catholic parishes, and an Orthodox ally with opinion 100.",
  "rip_church_latin_consent_button_tt": "25 ADM. Permit gradual conversion by the Union's centre; no immediate religion change. A recognized autonomous rite cannot be targeted.",
  "rip_church_recognize_rite_button_tt": "Pay 1 ADM per current development; recognize the rite for at least ten years. The centre may not convert this parish.",
  "rip_church_revoke_rite_button_tt": "After ten years, revoke the agreement. No refund; +3 local unrest for ten years and a new record of forced integration.",
  "rip_church_gc_infrastructure_button_tt": "20 Authority and 100 ducats (75 in Eastern orientation); ten years: -10% state maintenance, +5% clergy loyalty equilibrium. Move 10 toward the East.",
  "rip_church_gc_coexistence_button_tt": "Balanced orientation, 20 Authority and 100 ducats; ten years: -0.5 unrest, +10% improve relations.",
  "rip_church_gc_legate_button_tt": "Roman orientation, 30 Papal Standing and 100 ducats; ten years: +1 diplomatic reputation, +10% improve relations. Move 10 toward Rome.",
  "rip_church_gc_papal_support_button_tt": "30 Papal Standing and 100 ducats; ten years: +1 yearly legitimacy for monarchies, otherwise +1 yearly prestige. Move 10 toward Rome.",
  "rip_church_request_recognition_title": "Seek recognition of our patriarchate",
  "rip_church_request_recognition_desc": "Seek recognition within the wider Orthodox communion from 1589. Delay leaves the question open; rejection is a deliberate alternative schism. Constantinople need not be an independent state.",
  "rip_church_reconcile_title": "Reconcile with the eastern patriarchates",
  "rip_church_reconcile_desc": "Costs 100 DIP and 20 Authority. Negotiations last at least five years and conclude at peace with stability 1. Universal claims are renounced; internal discontent lasts ten years.",
  "rip_church_florence_title": "Sustain the Florentine union",
  "rip_church_florence_desc": "Alternative history, 1444–1501. Pay 200 ADM, 100 DIP and one year's income for five years of negotiations. Requires stability 2, peace and PAP opinion 100. Catholic patrons retain their state religion.",
  "rip_church_sponsor_union_title": "Sponsor an Eastern Catholic union",
  "rip_church_sponsor_union_desc": "From 1596, a Catholic crown may support an Eastern union without changing its state religion. Pay 100 ADM, 100 DIP and one year's income. One eligible core parish accepts the founding settlement; the others remain unchanged.",
  "rip_church_ecumenism_title": "Conclude the ecumenical settlement",
  "rip_church_ecumenism_desc": "Twenty years of union, ten years of balanced policy without forced conversion, stability 2, 60 Papal Standing, recognized Orthodox and Catholic parishes, and an Orthodox ally with opinion 100.",
  "rip_church_union_seat_title": "Found the single Centre of Union",
  "rip_church_union_seat_desc": "Only one centre exists worldwide. Costs 100 ADM and one year's income. Requires peace, stability 1, and a controlled Greek Catholic core with 10 development and a temple or cathedral. Twenty years between foundations.",
  "rip_church_icon_war_button": "Military Intercession",
  "rip_church_icon_war_button_tt": "+2.5% discipline; +5% manpower recovery. Activate for 10 Fervor; each icon may be reactivated only after one year. Deactivation is immediate and gives no refund.",
  "rip_church_icon_war_state": "[Root.GetChurchIconWar]",
  "rip_church_icon_mercy_button": "Mercy",
  "rip_church_icon_mercy_button_tt": "-1 unrest; -10% harsh treatment cost. Activate for 10 Fervor; each icon may be reactivated only after one year. Deactivation is immediate and gives no refund.",
  "rip_church_icon_mercy_state": "[Root.GetChurchIconMercy]",
  "rip_church_icon_building_button": "Church Building",
  "rip_church_icon_building_button_tt": "-5% development and building cost. Activate for 10 Fervor; each icon may be reactivated only after one year. Deactivation is immediate and gives no refund.",
  "rip_church_icon_building_state": "[Root.GetChurchIconBuilding]",
  "rip_church_icon_mission_button": "Apostolic Mission",
  "rip_church_icon_mission_button_tt": "+0.5 percentage points missionary strength; access to funded trade missions. Activate for 10 Fervor; each icon may be reactivated only after one year. Deactivation is immediate and gives no refund.",
  "rip_church_icon_mission_state": "[Root.GetChurchIconMission]",
  "rip_church_ro_heading_tt": "THE MUSCOVITE CHURCH\\n[Root.GetChurchROStatus]",
  "rip_church_ro_resources_tt": "Authority band: [Root.rip_church_pa_display.GetValue]%\\nIcons: [Root.rip_church_icons.GetValue] / [Root.rip_church_capacity.GetValue]   Fervor: [Root.rip_church_fervor.GetValue] / 100\\nMonthly fuel: +[Root.rip_church_fervor_income.GetValue] / -[Root.rip_church_fervor_cost.GetValue]   Missions: [Root.rip_church_nodes.GetValue]",
  "rip_church_ro_help_tt": "Authority supplies capacity; Fervor pays for active policies. Activation: 10 Fervor. Upkeep for 1/2/3/4 icons: 2/4/8/14 monthly, plus 2 per funded node. The newest icon closes first if capacity or fuel runs out.",
  "rip_church_gc_heading_tt": "THE UNION OF THE CHURCHES\\n[Root.GetChurchGCOrientation]",
  "rip_church_gc_resources_tt": "Communion Balance: [Root.rip_church_communion.GetValue] (-100 East / +100 Rome)\\nAuthority band: [Root.rip_church_pa_display.GetValue]%\\nPapal Standing: [Root.rip_church_papal_standing.GetValue] / 100\\nMonthly Standing: +[Root.rip_church_standing_income.GetValue]",
  "rip_church_gc_help_tt": "Authority belongs to the Eastern hierarchy. Papal Standing pays for limited Roman support. Shift policy by 20 for 25 ADM, once in five years. Recognize local rites from an owned province's panel; concessions protect stability but reduce direct taxation and recruitment.",
  "rip_church_gc_privilege_state_tt": "Active settlement: [Root.GetChurchPrivilege]",
  "rip_church_rite_heading_tt": "CONFESSIONAL AUTONOMY",
  "rip_church_rite_state_tt": "[Root.GetChurchRiteStatus]",
  "rip_church_rite_help_tt": "Recognizing a rite costs 1 ADM per current development. It excludes the parish from religious disunity, reduces unrest by 2, and reduces tax by 15% and manpower by 20%. The agreement lasts at least ten years. Revocation causes unrest for ten years.",
  "rip_church_icon_war_state_tt": "[Root.GetChurchIconWar]",
  "rip_church_icon_mercy_state_tt": "[Root.GetChurchIconMercy]",
  "rip_church_icon_building_state_tt": "[Root.GetChurchIconBuilding]",
  "rip_church_icon_mission_state_tt": "[Root.GetChurchIconMission]",
  "rip_church_icon_war": "icon war",
  "desc_rip_church_icon_war": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_icon_mercy": "icon mercy",
  "desc_rip_church_icon_mercy": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_icon_building": "icon building",
  "desc_rip_church_icon_building": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_icon_mission": "icon mission",
  "desc_rip_church_icon_mission": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_high": "ro high",
  "desc_rip_church_ro_high": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_max": "ro max",
  "desc_rip_church_ro_max": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_high_recognized": "ro high recognized",
  "desc_rip_church_ro_high_recognized": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_max_recognized": "ro max recognized",
  "desc_rip_church_ro_max_recognized": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_schism": "ro schism",
  "desc_rip_church_ro_schism": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_reconciliation_unrest": "reconciliation unrest",
  "desc_rip_church_reconciliation_unrest": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_infrastructure": "gc infrastructure",
  "desc_rip_church_gc_infrastructure": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_coexistence": "gc coexistence",
  "desc_rip_church_gc_coexistence": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_legate": "gc legate",
  "desc_rip_church_gc_legate": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_dynastic": "gc dynastic",
  "desc_rip_church_gc_dynastic": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_prestige": "gc prestige",
  "desc_rip_church_gc_prestige": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_rite": "rite",
  "desc_rip_church_rite": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_rite_favoured": "rite favoured",
  "desc_rip_church_rite_favoured": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_rite_ecumenical": "rite ecumenical",
  "desc_rip_church_rite_ecumenical": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_rite_revoked": "rite revoked",
  "desc_rip_church_rite_revoked": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_roman_resistance": "gc roman resistance",
  "desc_rip_church_gc_roman_resistance": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_conversion_resistance": "conversion resistance",
  "desc_rip_church_conversion_resistance": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_local_see": "gc local see",
  "desc_rip_church_gc_local_see": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_conversion_pressure": "conversion pressure",
  "desc_rip_church_conversion_pressure": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_0": "ro pa country 0",
  "desc_rip_church_ro_pa_country_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_0": "gc pa country 0",
  "desc_rip_church_gc_pa_country_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_0": "ro pa local 0",
  "desc_rip_church_ro_pa_local_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_0": "gc east pa local 0",
  "desc_rip_church_gc_east_pa_local_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_0": "gc middle pa local 0",
  "desc_rip_church_gc_middle_pa_local_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_0": "gc rome pa local 0",
  "desc_rip_church_gc_rome_pa_local_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_1": "ro pa country 1",
  "desc_rip_church_ro_pa_country_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_1": "gc pa country 1",
  "desc_rip_church_gc_pa_country_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_1": "ro pa local 1",
  "desc_rip_church_ro_pa_local_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_1": "gc east pa local 1",
  "desc_rip_church_gc_east_pa_local_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_1": "gc middle pa local 1",
  "desc_rip_church_gc_middle_pa_local_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_1": "gc rome pa local 1",
  "desc_rip_church_gc_rome_pa_local_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_2": "ro pa country 2",
  "desc_rip_church_ro_pa_country_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_2": "gc pa country 2",
  "desc_rip_church_gc_pa_country_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_2": "ro pa local 2",
  "desc_rip_church_ro_pa_local_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_2": "gc east pa local 2",
  "desc_rip_church_gc_east_pa_local_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_2": "gc middle pa local 2",
  "desc_rip_church_gc_middle_pa_local_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_2": "gc rome pa local 2",
  "desc_rip_church_gc_rome_pa_local_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_3": "ro pa country 3",
  "desc_rip_church_ro_pa_country_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_3": "gc pa country 3",
  "desc_rip_church_gc_pa_country_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_3": "ro pa local 3",
  "desc_rip_church_ro_pa_local_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_3": "gc east pa local 3",
  "desc_rip_church_gc_east_pa_local_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_3": "gc middle pa local 3",
  "desc_rip_church_gc_middle_pa_local_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_3": "gc rome pa local 3",
  "desc_rip_church_gc_rome_pa_local_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_4": "ro pa country 4",
  "desc_rip_church_ro_pa_country_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_4": "gc pa country 4",
  "desc_rip_church_gc_pa_country_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_4": "ro pa local 4",
  "desc_rip_church_ro_pa_local_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_4": "gc east pa local 4",
  "desc_rip_church_gc_east_pa_local_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_4": "gc middle pa local 4",
  "desc_rip_church_gc_middle_pa_local_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_4": "gc rome pa local 4",
  "desc_rip_church_gc_rome_pa_local_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_5": "ro pa country 5",
  "desc_rip_church_ro_pa_country_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_5": "gc pa country 5",
  "desc_rip_church_gc_pa_country_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_5": "ro pa local 5",
  "desc_rip_church_ro_pa_local_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_5": "gc east pa local 5",
  "desc_rip_church_gc_east_pa_local_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_5": "gc middle pa local 5",
  "desc_rip_church_gc_middle_pa_local_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_5": "gc rome pa local 5",
  "desc_rip_church_gc_rome_pa_local_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_6": "ro pa country 6",
  "desc_rip_church_ro_pa_country_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_6": "gc pa country 6",
  "desc_rip_church_gc_pa_country_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_6": "ro pa local 6",
  "desc_rip_church_ro_pa_local_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_6": "gc east pa local 6",
  "desc_rip_church_gc_east_pa_local_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_6": "gc middle pa local 6",
  "desc_rip_church_gc_middle_pa_local_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_6": "gc rome pa local 6",
  "desc_rip_church_gc_rome_pa_local_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_7": "ro pa country 7",
  "desc_rip_church_ro_pa_country_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_7": "gc pa country 7",
  "desc_rip_church_gc_pa_country_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_7": "ro pa local 7",
  "desc_rip_church_ro_pa_local_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_7": "gc east pa local 7",
  "desc_rip_church_gc_east_pa_local_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_7": "gc middle pa local 7",
  "desc_rip_church_gc_middle_pa_local_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_7": "gc rome pa local 7",
  "desc_rip_church_gc_rome_pa_local_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_8": "ro pa country 8",
  "desc_rip_church_ro_pa_country_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_8": "gc pa country 8",
  "desc_rip_church_gc_pa_country_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_8": "ro pa local 8",
  "desc_rip_church_ro_pa_local_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_8": "gc east pa local 8",
  "desc_rip_church_gc_east_pa_local_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_8": "gc middle pa local 8",
  "desc_rip_church_gc_middle_pa_local_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_8": "gc rome pa local 8",
  "desc_rip_church_gc_rome_pa_local_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_9": "ro pa country 9",
  "desc_rip_church_ro_pa_country_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_9": "gc pa country 9",
  "desc_rip_church_gc_pa_country_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_9": "ro pa local 9",
  "desc_rip_church_ro_pa_local_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_9": "gc east pa local 9",
  "desc_rip_church_gc_east_pa_local_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_9": "gc middle pa local 9",
  "desc_rip_church_gc_middle_pa_local_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_9": "gc rome pa local 9",
  "desc_rip_church_gc_rome_pa_local_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_10": "ro pa country 10",
  "desc_rip_church_ro_pa_country_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_10": "gc pa country 10",
  "desc_rip_church_gc_pa_country_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_10": "ro pa local 10",
  "desc_rip_church_ro_pa_local_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_10": "gc east pa local 10",
  "desc_rip_church_gc_east_pa_local_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_10": "gc middle pa local 10",
  "desc_rip_church_gc_middle_pa_local_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_10": "gc rome pa local 10",
  "desc_rip_church_gc_rome_pa_local_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_11": "ro pa country 11",
  "desc_rip_church_ro_pa_country_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_11": "gc pa country 11",
  "desc_rip_church_gc_pa_country_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_11": "ro pa local 11",
  "desc_rip_church_ro_pa_local_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_11": "gc east pa local 11",
  "desc_rip_church_gc_east_pa_local_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_11": "gc middle pa local 11",
  "desc_rip_church_gc_middle_pa_local_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_11": "gc rome pa local 11",
  "desc_rip_church_gc_rome_pa_local_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_12": "ro pa country 12",
  "desc_rip_church_ro_pa_country_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_12": "gc pa country 12",
  "desc_rip_church_gc_pa_country_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_12": "ro pa local 12",
  "desc_rip_church_ro_pa_local_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_12": "gc east pa local 12",
  "desc_rip_church_gc_east_pa_local_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_12": "gc middle pa local 12",
  "desc_rip_church_gc_middle_pa_local_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_12": "gc rome pa local 12",
  "desc_rip_church_gc_rome_pa_local_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_13": "ro pa country 13",
  "desc_rip_church_ro_pa_country_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_13": "gc pa country 13",
  "desc_rip_church_gc_pa_country_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_13": "ro pa local 13",
  "desc_rip_church_ro_pa_local_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_13": "gc east pa local 13",
  "desc_rip_church_gc_east_pa_local_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_13": "gc middle pa local 13",
  "desc_rip_church_gc_middle_pa_local_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_13": "gc rome pa local 13",
  "desc_rip_church_gc_rome_pa_local_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_14": "ro pa country 14",
  "desc_rip_church_ro_pa_country_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_14": "gc pa country 14",
  "desc_rip_church_gc_pa_country_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_14": "ro pa local 14",
  "desc_rip_church_ro_pa_local_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_14": "gc east pa local 14",
  "desc_rip_church_gc_east_pa_local_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_14": "gc middle pa local 14",
  "desc_rip_church_gc_middle_pa_local_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_14": "gc rome pa local 14",
  "desc_rip_church_gc_rome_pa_local_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_15": "ro pa country 15",
  "desc_rip_church_ro_pa_country_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_15": "gc pa country 15",
  "desc_rip_church_gc_pa_country_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_15": "ro pa local 15",
  "desc_rip_church_ro_pa_local_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_15": "gc east pa local 15",
  "desc_rip_church_gc_east_pa_local_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_15": "gc middle pa local 15",
  "desc_rip_church_gc_middle_pa_local_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_15": "gc rome pa local 15",
  "desc_rip_church_gc_rome_pa_local_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_16": "ro pa country 16",
  "desc_rip_church_ro_pa_country_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_16": "gc pa country 16",
  "desc_rip_church_gc_pa_country_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_16": "ro pa local 16",
  "desc_rip_church_ro_pa_local_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_16": "gc east pa local 16",
  "desc_rip_church_gc_east_pa_local_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_16": "gc middle pa local 16",
  "desc_rip_church_gc_middle_pa_local_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_16": "gc rome pa local 16",
  "desc_rip_church_gc_rome_pa_local_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_17": "ro pa country 17",
  "desc_rip_church_ro_pa_country_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_17": "gc pa country 17",
  "desc_rip_church_gc_pa_country_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_17": "ro pa local 17",
  "desc_rip_church_ro_pa_local_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_17": "gc east pa local 17",
  "desc_rip_church_gc_east_pa_local_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_17": "gc middle pa local 17",
  "desc_rip_church_gc_middle_pa_local_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_17": "gc rome pa local 17",
  "desc_rip_church_gc_rome_pa_local_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_18": "ro pa country 18",
  "desc_rip_church_ro_pa_country_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_18": "gc pa country 18",
  "desc_rip_church_gc_pa_country_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_18": "ro pa local 18",
  "desc_rip_church_ro_pa_local_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_18": "gc east pa local 18",
  "desc_rip_church_gc_east_pa_local_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_18": "gc middle pa local 18",
  "desc_rip_church_gc_middle_pa_local_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_18": "gc rome pa local 18",
  "desc_rip_church_gc_rome_pa_local_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_19": "ro pa country 19",
  "desc_rip_church_ro_pa_country_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_19": "gc pa country 19",
  "desc_rip_church_gc_pa_country_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_19": "ro pa local 19",
  "desc_rip_church_ro_pa_local_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_19": "gc east pa local 19",
  "desc_rip_church_gc_east_pa_local_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_19": "gc middle pa local 19",
  "desc_rip_church_gc_middle_pa_local_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_19": "gc rome pa local 19",
  "desc_rip_church_gc_rome_pa_local_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_20": "ro pa country 20",
  "desc_rip_church_ro_pa_country_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_20": "gc pa country 20",
  "desc_rip_church_gc_pa_country_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_20": "ro pa local 20",
  "desc_rip_church_ro_pa_local_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_20": "gc east pa local 20",
  "desc_rip_church_gc_east_pa_local_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_20": "gc middle pa local 20",
  "desc_rip_church_gc_middle_pa_local_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_20": "gc rome pa local 20",
  "desc_rip_church_gc_rome_pa_local_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_opinion_ro_recognized": "ro recognized",
  "rip_church_opinion_ro_unrecognized": "ro unrecognized",
  "rip_church_opinion_ro_schism": "ro schism",
  "rip_church_opinion_gc_catholic_east": "gc catholic east",
  "rip_church_opinion_gc_catholic_middle": "gc catholic middle",
  "rip_church_opinion_gc_catholic_rome": "gc catholic rome",
  "rip_church_opinion_gc_orthodox_east": "gc orthodox east",
  "rip_church_opinion_gc_orthodox_middle": "gc orthodox middle",
  "rip_church_opinion_gc_orthodox_rome": "gc orthodox rome",
  "rip_church_opinion_gc_ecumenical": "gc ecumenical",
  "rip_church_opinion_gc_ro_schism": "gc ro schism",
  "rip_church_opinion_propagation_conflict": "propagation conflict"
}

DATA.update({
 'rip_church_gc_guide_button': 'Guide',
 'rip_church_gc_native_guide_button': 'Guide',
 'rip_church_gc_guide_button_tt': 'How to use the Union panel: resources, policies, privileges and local rites. Opening this guide is free and changes nothing.',
 'rip_church_gc_native_guide_button_tt': 'Greek Catholics use Union privileges instead of Orthodox icons. Open the guide to the Union panel. Free; no policy changes.',
 'rip_church_help.1.t': 'The Union panel: resources',
 'rip_church_help.1.d': 'Greek Catholics manage communion with Rome through this panel; they do not select Orthodox icons.\\n\\nPatriarch Authority is shown in the main religion window and supports the Eastern hierarchy. Communion balance runs from -100 (Eastern autonomy) to +100 (Roman integration). The middle is balanced communion.\\n\\nPapal Standing is a separate reserve for Roman privileges. Monthly growth requires Rome to exist, peace with Rome and at least +50 opinion. The displayed rate explains when support is unavailable.',
 'rip_church_help.2.t': 'The Union panel: first actions',
 'rip_church_help.2.d': 'Toward the East / Toward Rome changes balance by 20 for 25 ADM, once every five years. You may also keep your current direction.\\n\\nChurch privileges opens the available contracts. Only one may run at a time, normally for ten years. Eastern privileges spend Authority and ducats; Roman privileges spend Papal Standing and ducats. Hover an option for its effects and exact price.\\n\\nGrey buttons mean a requirement is missing. Hover before paying; opening menus and this guide is free.',
 'rip_church_help.3.t': 'The Union panel: parishes and long-term goals',
 'rip_church_help.3.d': 'Select an owned Orthodox, Muscovite Orthodox or Catholic province to recognize its rite. Recognition costs one ADM per development, leaves its faith intact and trades tax and recruitment for stability. Revocation requires ten years.\\n\\nFound the Union seat creates the single world centre when an eligible parish, peace, stability and funding permit. Occupation suspends its work.\\n\\nEcumenical settlement is a late goal: a mature Union, sustained balance, Roman support, recognized Orthodox and Catholic rites and an Orthodox ally. Hover for the complete requirements.',
 'rip_church_help.actions': 'How do I use the buttons?',
 'rip_church_help.parishes': 'Local rites and long-term goals',
 'rip_church_help.back': 'Previous page',
 'rip_church_ro_heading': 'The Muscovite Church',
 'rip_church_ro_policies_title': 'Church policies',
 'rip_church_ro_policies_title_tt': 'Use the button below an icon to activate or deactivate its policy. Active icons have a lit frame. Hover each button for its effects and payment conditions.',
 'rip_church_icon_war_button': 'Military',
 'rip_church_icon_mercy_button': 'Mercy',
 'rip_church_icon_building_button': 'Building',
 'rip_church_icon_mission_button': 'Mission',
 'rip_church_ro_status': '[Root.GetChurchROStatus]',
 'rip_church_ro_resources': 'Fervor: [Root.rip_church_fervor.GetValue] / 100   Icons: [Root.rip_church_icons.GetValue] / [Root.rip_church_capacity.GetValue]\\nMonthly Fervor: +[Root.rip_church_fervor_income.GetValue] / -[Root.rip_church_fervor_cost.GetValue]\\nFunded trade nodes: [Root.rip_church_nodes.GetValue]',
 'rip_church_ro_mission_cost': 'Each trade node: 2 Fervor now + 2 per month\\nRequires an active Apostolic Mission',
 'rip_church_nodes_button': 'Fund / close trade missions',
 'rip_church_nodes_button_tt': 'Requires a funded node to manage, or an eligible node you can afford. Each node costs 2 Fervor immediately and 2 each month, in addition to icon upkeep. No ducat fee. Opening the menu itself makes no payment. Activate Apostolic Mission first; a new node requires at least 12 Fervor, a merchant, 50% trade power, connected church infrastructure and an eligible target.',
 'rip_church_mission_network_desc': 'Muscovite Orthodox missionary network. A registered node costs 2 Fervor now and 2 per month, in addition to Apostolic Mission upkeep. No ducat fee. Requires a merchant, 50% trade power and connected controlled church infrastructure. Fund or close nodes from the church panel.',
 'rip_church_break_communion_title': 'Renounce the patriarchal settlement',
 'rip_church_break_communion_desc': 'Deliberate alternative history: abandon recognized communion and claim an independent universal church. This enables a second funded mission node, increases confessional conflict and imposes -1 diplomatic reputation. Earlier reconciliation payments are not refunded.',
 'rip_church_oppose_union_title': 'Change our policy toward the Union',
 'rip_church_oppose_union_desc': 'For 25 DIP, adopt or end state opposition to the Union. Opposition multiplies its conversion target weights in our provinces by 0.25 and adds a mutual -10 opinion with Greek Catholic countries. The policy can be changed once every five years.',
 'rip_church_withdraw_union_support_title': 'Withdraw royal support for the Union',
 'rip_church_withdraw_union_support_desc': 'End the Catholic crown\'s patronage. Any Centre of Union under our rule loses its eligible patron and ceases to operate. Earlier foundation and negotiation payments are not refunded.',
 'rip_church_opinion_union_opposition': 'State opposition to the Union',
 'rip_church_center_active': 'Our Centre of Union is active',
 'rip_church_center_suspended': 'Our Centre is suspended by occupation',
 'rip_church_center_elsewhere': 'The single Centre is held by another country',
 'rip_church_center_absent': 'No Centre of Union is established',
 'rip_church_icon_no_fuel': 'Blocked: at least 10 Fervor is required.',
 'rip_church_icon_no_slot': 'Blocked: authority currently provides no vacant icon slot.',
 'rip_church_icon_cooldown': 'Blocked: one year must pass after the previous activation of this icon.',
 'rip_church_icon_can_activate': 'Ready to activate.',
 'rip_church_icon_can_deactivate': 'Active: click to deactivate without a refund.',
 'rip_church_ro_high': 'Centralized church administration',
 'rip_church_ro_max': 'Intensive church centralization',
 'rip_church_ro_high_recognized': 'Recognized central administration',
 'rip_church_ro_max_recognized': 'Recognized intensive centralization',
 'rip_church_ro_schism': 'Universal claims in schism',
 'rip_church_reconciliation_unrest': 'Opposition to reconciliation',
 'rip_church_gc_infrastructure': 'Eastern church infrastructure',
 'rip_church_gc_coexistence': 'Agreement on coexistence',
 'rip_church_gc_legate': 'Papal legate',
 'rip_church_gc_dynastic': 'Papal support for legitimacy',
 'rip_church_gc_prestige': 'Papal recognition of standing',
 'rip_church_rite': 'Confessional autonomy',
 'rip_church_rite_favoured': 'Protected local tradition',
 'rip_church_rite_ecumenical': 'Ecumenical accommodation',
 'rip_church_rite_revoked': 'Revoked confessional autonomy',
 'rip_church_gc_roman_resistance': 'Resistance to Roman integration',
 'rip_church_conversion_resistance': 'Resistance to jurisdictional pressure',
 'rip_church_gc_local_see': 'Local Eastern Catholic see',
 'rip_church_conversion_pressure': 'Recent missionary pressure',
 'rip_church_opinion_ro_recognized': 'Recognized Orthodox communion',
 'rip_church_opinion_ro_unrecognized': 'Shared faith, disputed jurisdiction',
 'rip_church_opinion_ro_schism': 'Rival universal claims',
 'rip_church_opinion_gc_catholic_east': 'Communion with Eastern autonomy',
 'rip_church_opinion_gc_catholic_middle': 'Balanced communion with Rome',
 'rip_church_opinion_gc_catholic_rome': 'Close Roman communion',
 'rip_church_opinion_gc_orthodox_east': 'Respect for Eastern tradition',
 'rip_church_opinion_gc_orthodox_middle': 'Balanced confessional relations',
 'rip_church_opinion_gc_orthodox_rome': 'Rivalry over Roman integration',
 'rip_church_opinion_gc_ecumenical': 'Ecumenical settlement',
 'rip_church_opinion_gc_ro_schism': 'Conflicting ecclesiastical claims',
 'rip_church_opinion_propagation_conflict': 'Missionary intervention in our parishes',
})
for key in ('heading','status','resources','mission_cost'):
 DATA['rip_church_ro_'+key+'_tt']=DATA['rip_church_ro_'+key]
for icon in ('war','mercy','building','mission'):
    DATA['rip_church_icon_'+icon]=DATA['rip_church_icon_'+icon+'_button']
    DATA['desc_rip_church_icon_'+icon]=DATA['rip_church_icon_'+icon+'_button_tt']
    DATA['rip_church_icon_'+icon+'_button_tt']+='\\n[Root.GetChurchIcon'+icon.title()+'Access]'
DATA.update({
 'rip_church_gc_heading': 'Union of the Churches',
 'rip_church_gc_orientation': '[Root.GetChurchGCOrientation]',
 'rip_church_gc_resources': 'Communion balance: [Root.rip_church_communion.GetValue]\\nPapal Standing: [Root.rip_church_papal_standing.GetValue] / 100\\nMonthly rate: [Root.GetChurchStandingRate]',
 'rip_church_gc_parishes': 'Recognized parishes: [Root.rip_church_recognized_parishes.GetValue]',
 'rip_church_gc_center_state': '[Root.GetChurchCenterStatus]',
 'rip_church_gc_policy_label': 'EASTERN AUTONOMY  /  ROMAN COMMUNION',
 'rip_church_gc_policy_cost': '25 ADM  |  20 balance  |  Once every 5 years',
 'rip_church_gc_privilege_state': 'ACTIVE SETTLEMENT\\n[Root.GetChurchPrivilege]',
 'rip_church_gc_help': 'Local rites: select an owned province. Hover actions for conditions.',
 'rip_church_ecumenism_button': 'Ecumenical settlement',
 'rip_church_standing_rate_zero': '+0.00 (Roman support unavailable)',
 'rip_church_standing_rate_east': '+0.10',
 'rip_church_standing_rate_middle': '+0.25',
 'rip_church_standing_rate_rome': '+0.50',
})
for key in ('heading','orientation','resources','parishes','center_state','policy_label','policy_cost','privilege_state'):
 DATA['rip_church_gc_'+key+'_tt']=DATA['rip_church_gc_'+key]
DATA['rip_church_gc_resources_tt']+='\\nBalance runs from -100 (East) to +100 (Rome).\\nStanding grows only with Rome present, at peace with you, and at least +50 opinion.\\nPatriarch Authority is shown by the main religion window.'
DATA['rip_church_nodes.1.d']+=' Requires Cradle of Civilization; without that DLC, no node can be funded.'
DATA['rip_church_center_button_tt']+=' Occupation suspends the centre and reserves the world slot. Liberation restarts native conversion; its previous in-flight progress may be lost.'
for key in list(DATA):
    match=re.fullmatch(r'rip_church_(ro|gc)(?:_(east|middle|rome))?_pa_(country|local)_(\d+)',key)
    if match:
        DATA[key]='Church authority adjustment: '+str(int(match[4])*5)+'%'
        DATA['desc_'+key]='Offsets the inherited Orthodox authority bonus for this confession. Recalculated in five-point authority bands; the native Orthodox faith is unchanged.'

ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args()
# Generated variable/modifier definitions may add display-only compensation IDs.
for p in (ROOT/'common/event_modifiers').glob('RIP_church*.txt'):
    for key in re.findall(r'(?m)^(\w+)\s*=\s*\{',p.read_text(encoding='utf-8-sig')):
        DATA.setdefault(key,key.removeprefix('rip_church_').replace('_',' ').title())
        DATA.setdefault('desc_'+key,'Part of the current ecclesiastical settlement. Numerical adjustments follow authority and orientation.')
def defined(name,rows):
    result=f'defined_text = {{\n name = {name}\n'
    for trigger,key in rows:
        result+=f' text = {{ trigger = {{ {trigger} }} localisation_key = {key} }}\n'
    return result+'}\n'
custom=defined('GetChurchROStatus',[
 ('has_country_flag = rip_church_reconciliation_pending','rip_church_ro_reconciling'),
 ('has_country_flag = rip_church_ro_schismatic','rip_church_ro_schismatic'),
 ('rip_church_ro_recognized = yes','rip_church_ro_recognized'),
 ('has_country_flag = rip_church_ro_provisional','rip_church_ro_provisional'),
 ('always = yes','rip_church_ro_unrecognized')])
custom+=defined('GetChurchStandingRate',[
 ('NOT = { exists = PAP NOT = { war_with = PAP } PAP = { has_opinion = { who = ROOT value = 50 } } }','rip_church_standing_rate_zero'),
 ('rip_church_gc_eastern = yes','rip_church_standing_rate_east'),
 ('rip_church_gc_roman = yes','rip_church_standing_rate_rome'),
 ('always = yes','rip_church_standing_rate_middle')])
custom+=defined('GetChurchGCOrientation',[
 ('rip_church_gc_eastern = yes','rip_church_gc_east'),
 ('rip_church_gc_roman = yes','rip_church_gc_rome'),
 ('always = yes','rip_church_gc_middle')])
custom+=defined('GetChurchPrivilege',[(f'has_country_modifier = rip_church_gc_{key}',f'rip_church_gc_{key}') for key in ('infrastructure','coexistence','legate','dynastic','prestige')]+[('always = yes','rip_church_none')])
custom+=defined('GetChurchCenterStatus',[
 ('any_owned_province = { has_province_flag = rip_church_center_suspended }','rip_church_center_suspended'),
 ('any_owned_province = { rip_church_center_alive = yes }','rip_church_center_active'),
 ('any_province = { religion = greek_catholic OR = { is_reformation_center = yes has_province_flag = rip_church_center_suspended } }','rip_church_center_elsewhere'),
 ('always = yes','rip_church_center_absent')])
custom+=defined('GetChurchRiteStatus',[
 ('has_province_flag = rip_church_rite_recognized','rip_church_rite_recognized'),
 ('has_province_flag = rip_church_latin_consent','rip_church_rite_consent'),
 ('always = yes','rip_church_rite_unrecognized')])
for key in ('war','mercy','building','mission'):
    custom+=defined('GetChurchIcon'+key.title(),[(f'has_country_flag = rip_church_icon_{key}','rip_church_active'),('always = yes','rip_church_inactive')])
    custom+=defined('GetChurchIcon'+key.title()+'Access',[
        (f'has_country_flag = rip_church_icon_{key}','rip_church_icon_can_deactivate'),
        ('NOT = { check_variable = { which = rip_church_fervor value = 10 } }','rip_church_icon_no_fuel'),
        ('NOT = { rip_church_ro_slot_available = yes }','rip_church_icon_no_slot'),
        (f'has_country_flag = rip_church_icon_{key}_used NOT = {{ had_country_flag = {{ flag = rip_church_icon_{key}_used days = 365 }} }}','rip_church_icon_cooldown'),
        ('always = yes','rip_church_icon_can_activate')])
outputs={'customizable_localization/rip_church_redesign.txt':custom}
for lang in ('english','french','german','spanish'):
    outputs[f'localisation/replace/zzzz_RIP_church_redesign_l_{lang}.yml']='\ufeffl_'+lang+':\n'+''.join(f' {k}:0 "{v.replace(chr(34),chr(39))}"\n' for k,v in sorted(DATA.items()))
stale=[]
for path,text in outputs.items():
    p=ROOT/path
    if not p.exists() or p.read_text(encoding='utf-8')!=text:
        stale.append(path)
        if not args.check:
            p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8',newline='\n')
print(('STALE' if args.check and stale else 'GENERATED')+f': {len(DATA)} keys; {len(stale)} files')
if args.check and stale: raise SystemExit(1)
