"""Generate church UI localisation and fallback strings; no claim of translated fallback text."""
from pathlib import Path
import json,argparse,re
ROOT=Path(__file__).resolve().parents[1]
DATA={
  "rip_church_close": "Close",
  "rip_church.2.t": "Moscow and the Third Rome",
  "rip_church.2.d": "Writers at the Muscovite court describe Moscow as a guardian of the Orthodox inheritance. This sixteenth-century political theology does not itself create a new creed or end communion with the eastern patriarchates. Universal jurisdiction would require a separate, deliberate claim.",
  "rip_church.2.a": "Cultivate the Third Rome ideal",
  "rip_church.2.b": "Emphasize our place among the Orthodox churches",
  "rip_church.3.t": "A Recognized Patriarchate",
  "rip_church.3.d": "The ecclesiastical settlement recognizes our patriarchate within the wider Orthodox communion. Moscow accepts its place after the four ancient eastern patriarchates. Our centralized church remains a distinct political institution; recognition does not abolish its internal responsibilities.",
  "rip_church.5.t": "The Florentine Settlement Endures",
  "rip_church.5.d": "Our negotiated settlement has sustained a union that historically failed to gain lasting general acceptance. This is an alternative historical path: the Byzantine rite and its bishops remain, while communion with Rome is accepted. Parish integration will proceed locally.",
  "rip_church.6.t": "The Institutions of Communion",
  "rip_church.6.d": "Only one ten-year privilege may operate at a time. Eastern institutions draw on internal church authority; Roman support draws on Papal Standing. All options cost money. The position of Communion Balance determines which instruments are available.",
  "rip_church_recognition_refuse": "Claim an independent universal church — alternative history",
  "rip_church_nodes.1.t": "Fund the Missionary Network",
  "rip_church_nodes.1.d": "Register an eligible node, then select Missionary Network in its native merchant policies. Registration prepays 2 Fervor and reserves 2 Fervor each month until closed, even if a different trade policy is selected. Each node needs a merchant, 50% trade power, a controlled core parish with a temple connected to the capital's Muscovite church, and neighbouring missionary targets. One node is allowed; the schismatic branch allows two.",
  "rip_church_mission_network": "Missionary Network",
  "rip_church_mission_network_desc": "A funded network of monasteries, traders and frontier parishes. Requires a registered node, merchant, 50% trade power, connected controlled church infrastructure and an active Apostolic Mission. Conversion is gradual.",
  "rip_church_ro_heading": "THE MUSCOVITE CHURCH\\n[Root.GetChurchROStatus]",
  "rip_church_ro_resources": "Authority band: [Root.rip_church_pa_display.GetValue]%\\nIcons: [Root.rip_church_icons.GetValue] / [Root.rip_church_capacity.GetValue]   Fervor: [Root.rip_church_fervor.GetValue] / 100\\nMonthly fuel: +[Root.rip_church_fervor_income.GetValue] / -[Root.rip_church_fervor_cost.GetValue]   Missions: [Root.rip_church_nodes.GetValue]",
  "rip_church_ro_help": "Authority supplies capacity; Fervor pays for active policies. Activation: 10 Fervor. Upkeep for 1/2/3/4 icons: 2/4/8/14 monthly, plus 2 per funded node. The newest icon closes first if capacity or fuel runs out.",
  "rip_church_gc_heading": "THE UNION OF THE CHURCHES\\n[Root.GetChurchGCOrientation]",
  "rip_church_gc_resources": "Communion Balance: [Root.rip_church_communion.GetValue] (-100 East / +100 Rome)\\nAuthority band: [Root.rip_church_pa_display.GetValue]%\\nPapal Standing: [Root.rip_church_papal_standing.GetValue] / 100\\nMonthly Standing: +[Root.rip_church_standing_income.GetValue]",
  "rip_church_gc_help": "Authority belongs to the Eastern hierarchy. Papal Standing pays for limited Roman support. Shift policy by 20 for 25 ADM, once in five years. Recognize local rites from an owned province's panel; concessions protect stability but reduce direct taxation and recruitment.",
  "rip_church_gc_privilege_state": "Active settlement: [Root.GetChurchPrivilege]",
  "rip_church_east_button": "Favor the East",
  "rip_church_rome_button": "Favor Rome",
  "rip_church_nodes_button": "Missionary networks",
  "rip_church_reconcile_button": "Negotiate reconciliation",
  "rip_church_privileges_button": "Church privileges",
  "rip_church_center_button": "Found the Union's seat",
  "rip_church_ecumenism_button": "Conclude ecumenical settlement",
  "rip_church_gc_infrastructure_button": "Eastern infrastructure",
  "rip_church_gc_coexistence_button": "Agreement of coexistence",
  "rip_church_gc_legate_button": "Request a papal legate",
  "rip_church_gc_papal_support_button": "Request dynastic / moral support",
  "rip_church_rite_heading": "CONFESSIONAL AUTONOMY",
  "rip_church_rite_state": "[Root.GetChurchRiteStatus]",
  "rip_church_rite_help": "Recognizing a rite costs 1 ADM per current development. It excludes the parish from religious disunity, reduces unrest by 2, and reduces tax by 15% and manpower by 20%. The agreement lasts at least ten years. Revocation causes unrest for ten years.",
  "rip_church_recognize_rite_button": "Recognize the local rite",
  "rip_church_revoke_rite_button": "Revoke confessional autonomy",
  "rip_church_latin_consent_button": "Consent to Byzantine integration",
  "rip_church_rite_affordable_tt": "Our treasury of administrative power covers 1 ADM per development of this province.",
  "rip_church_ro_unrecognized": "Unrecognized autocephaly",
  "rip_church_ro_provisional": "Patriarchate recognized; conciliar confirmation pending",
  "rip_church_ro_recognized": "Recognized patriarchate within Orthodox communion",
  "rip_church_ro_schismatic": "Independent Third Rome church — alternative history",
  "rip_church_ro_reconciling": "Reconciliation under negotiation",
  "rip_church_gc_east": "Eastern autonomy",
  "rip_church_gc_middle": "Balanced communion",
  "rip_church_gc_rome": "Roman integration",
  "rip_church_active": "ACTIVE",
  "rip_church_inactive": "Inactive",
  "rip_church_none": "None",
  "rip_church_rite_recognized": "The local rite has a binding agreement of confessional autonomy.",
  "rip_church_rite_unrecognized": "The local rite has no agreement of confessional autonomy.",
  "rip_church_rite_consent": "The Latin parish has consented to gradual Byzantine integration.",
  "rip_church_nodes_button_tt": "Register or close missionary networks. Registration prepays 2 Fervor; each registered node reserves 2 per month. Choose the native Missionary Network trade policy after funding.",
  "rip_church_reconcile_button_tt": "Costs 100 DIP and 20 Authority. Negotiations last at least five years and conclude at peace with stability 1. Universal claims are renounced; internal discontent lasts ten years.",
  "rip_church_east_button_tt": "Costs 25 ADM; move 20 toward Eastern autonomy. Five-year policy interval. Existing contracts keep their original expiry.",
  "rip_church_rome_button_tt": "Costs 25 ADM; move 20 toward Roman integration. Five-year policy interval. Existing contracts keep their original expiry.",
  "rip_church_center_button_tt": "Only one centre exists worldwide. Costs 100 ADM and one year's income. Requires peace, stability 1, and a controlled Greek Catholic core with 10 development and a temple or cathedral. Twenty years between foundations.",
  "rip_church_privileges_button_tt": "Choose one ten-year church privilege. Eastern options require 20 Authority; Roman options require 30 Papal Standing and good relations with PAP. Standard price: 100 ducats; Eastern infrastructure costs 75 under Eastern orientation.",
  "rip_church_ecumenism_button_tt": "Twenty years of union, ten years of balanced policy without forced conversion, stability 2, 60 Papal Standing, recognized Orthodox and Catholic parishes, and an Orthodox ally with opinion 100.",
  "rip_church_latin_consent_button_tt": "25 ADM. Permit gradual conversion by the Union's centre; no immediate religion change. A recognized autonomous rite cannot be targeted.",
  "rip_church_recognize_rite_button_tt": "Pay 1 ADM per current development; recognize the rite for at least ten years. The centre may not convert this parish.",
  "rip_church_revoke_rite_button_tt": "After ten years, revoke the agreement. No refund; +3 local unrest for ten years and a new record of forced integration.",
  "rip_church_gc_infrastructure_button_tt": "20 Authority and 100 ducats (75 in Eastern orientation); ten years: -10% state maintenance, +5% clergy loyalty equilibrium. Move 10 toward the East.",
  "rip_church_gc_coexistence_button_tt": "Balanced orientation, 20 Authority and 100 ducats; ten years: -0.5 unrest, +10% improve relations.",
  "rip_church_gc_legate_button_tt": "Roman orientation, 30 Papal Standing and 100 ducats; ten years: +1 diplomatic reputation, +10% improve relations. Move 10 toward Rome.",
  "rip_church_gc_papal_support_button_tt": "30 Papal Standing and 100 ducats; ten years: +1 yearly legitimacy for monarchies, otherwise +1 yearly prestige. Move 10 toward Rome.",
  "rip_church_request_recognition_title": "Seek recognition of our patriarchate",
  "rip_church_request_recognition_desc": "Seek recognition within the wider Orthodox communion from 1589. Delay leaves the question open; rejection is a deliberate alternative schism. Constantinople need not be an independent state.",
  "rip_church_reconcile_title": "Reconcile with the eastern patriarchates",
  "rip_church_reconcile_desc": "Costs 100 DIP and 20 Authority. Negotiations last at least five years and conclude at peace with stability 1. Universal claims are renounced; internal discontent lasts ten years.",
  "rip_church_florence_title": "Sustain the Florentine union",
  "rip_church_florence_desc": "Alternative history, 1444-1501. The 1439 Florentine union is an earlier, separate path from the 1596 Union of Brest. Pay 200 ADM, 100 DIP and one year's income for five years of negotiations. Requires stability 2, peace and PAP opinion 100. The Eastern hierarchy keeps its rite while entering communion with Rome; Catholic patrons retain their state religion.",
  "rip_church_sponsor_union_title": "Sponsor an Eastern Catholic union",
  "rip_church_sponsor_union_desc": "From 1596, a Catholic crown may support an Eastern union without changing its state religion. Pay 100 ADM, 100 DIP and one year's income. One eligible core parish accepts the founding settlement; the others remain unchanged.",
  "rip_church_ecumenism_title": "Conclude the ecumenical settlement",
  "rip_church_ecumenism_desc": "Twenty years of union, ten years of balanced policy without forced conversion, stability 2, 60 Papal Standing, recognized Orthodox and Catholic parishes, and an Orthodox ally with opinion 100.",
  "rip_church_union_seat_title": "Found the single Centre of Union",
  "rip_church_union_seat_desc": "Only one centre exists worldwide. Costs 100 ADM and one year's income. Requires peace, stability 1, and a controlled Greek Catholic core with 10 development and a temple or cathedral. Twenty years between foundations.",
  "rip_church_icon_war_button": "Military Intercession",
  "rip_church_icon_war_button_tt": "+2.5% discipline; +5% manpower recovery. Activate for 10 Fervor; each icon may be reactivated only after one year. Deactivation is immediate and gives no refund.",
  "rip_church_icon_war_state": "[Root.GetChurchIconWar]",
  "rip_church_icon_mercy_button": "Mercy",
  "rip_church_icon_mercy_button_tt": "-1 unrest; -10% harsh treatment cost. Activate for 10 Fervor; each icon may be reactivated only after one year. Deactivation is immediate and gives no refund.",
  "rip_church_icon_mercy_state": "[Root.GetChurchIconMercy]",
  "rip_church_icon_building_button": "Church Building",
  "rip_church_icon_building_button_tt": "-5% development and building cost. Activate for 10 Fervor; each icon may be reactivated only after one year. Deactivation is immediate and gives no refund.",
  "rip_church_icon_building_state": "[Root.GetChurchIconBuilding]",
  "rip_church_icon_mission_button": "Apostolic Mission",
  "rip_church_icon_mission_button_tt": "+0.5 percentage points missionary strength; access to funded trade missions. Activate for 10 Fervor; each icon may be reactivated only after one year. Deactivation is immediate and gives no refund.",
  "rip_church_icon_mission_state": "[Root.GetChurchIconMission]",
  "rip_church_ro_heading_tt": "THE MUSCOVITE CHURCH\\n[Root.GetChurchROStatus]",
  "rip_church_ro_resources_tt": "Authority band: [Root.rip_church_pa_display.GetValue]%\\nIcons: [Root.rip_church_icons.GetValue] / [Root.rip_church_capacity.GetValue]   Fervor: [Root.rip_church_fervor.GetValue] / 100\\nMonthly fuel: +[Root.rip_church_fervor_income.GetValue] / -[Root.rip_church_fervor_cost.GetValue]   Missions: [Root.rip_church_nodes.GetValue]",
  "rip_church_ro_help_tt": "Authority supplies capacity; Fervor pays for active policies. Activation: 10 Fervor. Upkeep for 1/2/3/4 icons: 2/4/8/14 monthly, plus 2 per funded node. The newest icon closes first if capacity or fuel runs out.",
  "rip_church_gc_heading_tt": "THE UNION OF THE CHURCHES\\n[Root.GetChurchGCOrientation]",
  "rip_church_gc_resources_tt": "Communion Balance: [Root.rip_church_communion.GetValue] (-100 East / +100 Rome)\\nAuthority band: [Root.rip_church_pa_display.GetValue]%\\nPapal Standing: [Root.rip_church_papal_standing.GetValue] / 100\\nMonthly Standing: +[Root.rip_church_standing_income.GetValue]",
  "rip_church_gc_help_tt": "Authority belongs to the Eastern hierarchy. Papal Standing pays for limited Roman support. Shift policy by 20 for 25 ADM, once in five years. Recognize local rites from an owned province's panel; concessions protect stability but reduce direct taxation and recruitment.",
  "rip_church_gc_privilege_state_tt": "Active settlement: [Root.GetChurchPrivilege]",
  "rip_church_rite_heading_tt": "CONFESSIONAL AUTONOMY",
  "rip_church_rite_state_tt": "[Root.GetChurchRiteStatus]",
  "rip_church_rite_help_tt": "Recognizing a rite costs 1 ADM per current development. It excludes the parish from religious disunity, reduces unrest by 2, and reduces tax by 15% and manpower by 20%. The agreement lasts at least ten years. Revocation causes unrest for ten years.",
  "rip_church_icon_war_state_tt": "[Root.GetChurchIconWar]",
  "rip_church_icon_mercy_state_tt": "[Root.GetChurchIconMercy]",
  "rip_church_icon_building_state_tt": "[Root.GetChurchIconBuilding]",
  "rip_church_icon_mission_state_tt": "[Root.GetChurchIconMission]",
  "rip_church_icon_war": "icon war",
  "desc_rip_church_icon_war": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_icon_mercy": "icon mercy",
  "desc_rip_church_icon_mercy": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_icon_building": "icon building",
  "desc_rip_church_icon_building": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_icon_mission": "icon mission",
  "desc_rip_church_icon_mission": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_high": "ro high",
  "desc_rip_church_ro_high": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_max": "ro max",
  "desc_rip_church_ro_max": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_high_recognized": "ro high recognized",
  "desc_rip_church_ro_high_recognized": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_max_recognized": "ro max recognized",
  "desc_rip_church_ro_max_recognized": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_schism": "ro schism",
  "desc_rip_church_ro_schism": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_reconciliation_unrest": "reconciliation unrest",
  "desc_rip_church_reconciliation_unrest": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_infrastructure": "gc infrastructure",
  "desc_rip_church_gc_infrastructure": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_coexistence": "gc coexistence",
  "desc_rip_church_gc_coexistence": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_legate": "gc legate",
  "desc_rip_church_gc_legate": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_dynastic": "gc dynastic",
  "desc_rip_church_gc_dynastic": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_prestige": "gc prestige",
  "desc_rip_church_gc_prestige": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_rite": "rite",
  "desc_rip_church_rite": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_rite_favoured": "rite favoured",
  "desc_rip_church_rite_favoured": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_rite_ecumenical": "rite ecumenical",
  "desc_rip_church_rite_ecumenical": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_rite_revoked": "rite revoked",
  "desc_rip_church_rite_revoked": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_roman_resistance": "gc roman resistance",
  "desc_rip_church_gc_roman_resistance": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_conversion_resistance": "conversion resistance",
  "desc_rip_church_conversion_resistance": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_local_see": "gc local see",
  "desc_rip_church_gc_local_see": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_conversion_pressure": "conversion pressure",
  "desc_rip_church_conversion_pressure": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_0": "ro pa country 0",
  "desc_rip_church_ro_pa_country_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_0": "gc pa country 0",
  "desc_rip_church_gc_pa_country_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_0": "ro pa local 0",
  "desc_rip_church_ro_pa_local_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_0": "gc east pa local 0",
  "desc_rip_church_gc_east_pa_local_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_0": "gc middle pa local 0",
  "desc_rip_church_gc_middle_pa_local_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_0": "gc rome pa local 0",
  "desc_rip_church_gc_rome_pa_local_0": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_1": "ro pa country 1",
  "desc_rip_church_ro_pa_country_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_1": "gc pa country 1",
  "desc_rip_church_gc_pa_country_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_1": "ro pa local 1",
  "desc_rip_church_ro_pa_local_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_1": "gc east pa local 1",
  "desc_rip_church_gc_east_pa_local_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_1": "gc middle pa local 1",
  "desc_rip_church_gc_middle_pa_local_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_1": "gc rome pa local 1",
  "desc_rip_church_gc_rome_pa_local_1": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_2": "ro pa country 2",
  "desc_rip_church_ro_pa_country_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_2": "gc pa country 2",
  "desc_rip_church_gc_pa_country_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_2": "ro pa local 2",
  "desc_rip_church_ro_pa_local_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_2": "gc east pa local 2",
  "desc_rip_church_gc_east_pa_local_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_2": "gc middle pa local 2",
  "desc_rip_church_gc_middle_pa_local_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_2": "gc rome pa local 2",
  "desc_rip_church_gc_rome_pa_local_2": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_3": "ro pa country 3",
  "desc_rip_church_ro_pa_country_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_3": "gc pa country 3",
  "desc_rip_church_gc_pa_country_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_3": "ro pa local 3",
  "desc_rip_church_ro_pa_local_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_3": "gc east pa local 3",
  "desc_rip_church_gc_east_pa_local_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_3": "gc middle pa local 3",
  "desc_rip_church_gc_middle_pa_local_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_3": "gc rome pa local 3",
  "desc_rip_church_gc_rome_pa_local_3": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_4": "ro pa country 4",
  "desc_rip_church_ro_pa_country_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_4": "gc pa country 4",
  "desc_rip_church_gc_pa_country_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_4": "ro pa local 4",
  "desc_rip_church_ro_pa_local_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_4": "gc east pa local 4",
  "desc_rip_church_gc_east_pa_local_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_4": "gc middle pa local 4",
  "desc_rip_church_gc_middle_pa_local_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_4": "gc rome pa local 4",
  "desc_rip_church_gc_rome_pa_local_4": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_5": "ro pa country 5",
  "desc_rip_church_ro_pa_country_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_5": "gc pa country 5",
  "desc_rip_church_gc_pa_country_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_5": "ro pa local 5",
  "desc_rip_church_ro_pa_local_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_5": "gc east pa local 5",
  "desc_rip_church_gc_east_pa_local_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_5": "gc middle pa local 5",
  "desc_rip_church_gc_middle_pa_local_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_5": "gc rome pa local 5",
  "desc_rip_church_gc_rome_pa_local_5": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_6": "ro pa country 6",
  "desc_rip_church_ro_pa_country_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_6": "gc pa country 6",
  "desc_rip_church_gc_pa_country_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_6": "ro pa local 6",
  "desc_rip_church_ro_pa_local_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_6": "gc east pa local 6",
  "desc_rip_church_gc_east_pa_local_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_6": "gc middle pa local 6",
  "desc_rip_church_gc_middle_pa_local_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_6": "gc rome pa local 6",
  "desc_rip_church_gc_rome_pa_local_6": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_7": "ro pa country 7",
  "desc_rip_church_ro_pa_country_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_7": "gc pa country 7",
  "desc_rip_church_gc_pa_country_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_7": "ro pa local 7",
  "desc_rip_church_ro_pa_local_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_7": "gc east pa local 7",
  "desc_rip_church_gc_east_pa_local_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_7": "gc middle pa local 7",
  "desc_rip_church_gc_middle_pa_local_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_7": "gc rome pa local 7",
  "desc_rip_church_gc_rome_pa_local_7": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_8": "ro pa country 8",
  "desc_rip_church_ro_pa_country_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_8": "gc pa country 8",
  "desc_rip_church_gc_pa_country_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_8": "ro pa local 8",
  "desc_rip_church_ro_pa_local_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_8": "gc east pa local 8",
  "desc_rip_church_gc_east_pa_local_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_8": "gc middle pa local 8",
  "desc_rip_church_gc_middle_pa_local_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_8": "gc rome pa local 8",
  "desc_rip_church_gc_rome_pa_local_8": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_9": "ro pa country 9",
  "desc_rip_church_ro_pa_country_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_9": "gc pa country 9",
  "desc_rip_church_gc_pa_country_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_9": "ro pa local 9",
  "desc_rip_church_ro_pa_local_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_9": "gc east pa local 9",
  "desc_rip_church_gc_east_pa_local_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_9": "gc middle pa local 9",
  "desc_rip_church_gc_middle_pa_local_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_9": "gc rome pa local 9",
  "desc_rip_church_gc_rome_pa_local_9": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_10": "ro pa country 10",
  "desc_rip_church_ro_pa_country_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_10": "gc pa country 10",
  "desc_rip_church_gc_pa_country_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_10": "ro pa local 10",
  "desc_rip_church_ro_pa_local_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_10": "gc east pa local 10",
  "desc_rip_church_gc_east_pa_local_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_10": "gc middle pa local 10",
  "desc_rip_church_gc_middle_pa_local_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_10": "gc rome pa local 10",
  "desc_rip_church_gc_rome_pa_local_10": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_11": "ro pa country 11",
  "desc_rip_church_ro_pa_country_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_11": "gc pa country 11",
  "desc_rip_church_gc_pa_country_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_11": "ro pa local 11",
  "desc_rip_church_ro_pa_local_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_11": "gc east pa local 11",
  "desc_rip_church_gc_east_pa_local_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_11": "gc middle pa local 11",
  "desc_rip_church_gc_middle_pa_local_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_11": "gc rome pa local 11",
  "desc_rip_church_gc_rome_pa_local_11": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_12": "ro pa country 12",
  "desc_rip_church_ro_pa_country_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_12": "gc pa country 12",
  "desc_rip_church_gc_pa_country_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_12": "ro pa local 12",
  "desc_rip_church_ro_pa_local_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_12": "gc east pa local 12",
  "desc_rip_church_gc_east_pa_local_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_12": "gc middle pa local 12",
  "desc_rip_church_gc_middle_pa_local_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_12": "gc rome pa local 12",
  "desc_rip_church_gc_rome_pa_local_12": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_13": "ro pa country 13",
  "desc_rip_church_ro_pa_country_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_13": "gc pa country 13",
  "desc_rip_church_gc_pa_country_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_13": "ro pa local 13",
  "desc_rip_church_ro_pa_local_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_13": "gc east pa local 13",
  "desc_rip_church_gc_east_pa_local_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_13": "gc middle pa local 13",
  "desc_rip_church_gc_middle_pa_local_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_13": "gc rome pa local 13",
  "desc_rip_church_gc_rome_pa_local_13": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_14": "ro pa country 14",
  "desc_rip_church_ro_pa_country_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_14": "gc pa country 14",
  "desc_rip_church_gc_pa_country_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_14": "ro pa local 14",
  "desc_rip_church_ro_pa_local_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_14": "gc east pa local 14",
  "desc_rip_church_gc_east_pa_local_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_14": "gc middle pa local 14",
  "desc_rip_church_gc_middle_pa_local_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_14": "gc rome pa local 14",
  "desc_rip_church_gc_rome_pa_local_14": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_15": "ro pa country 15",
  "desc_rip_church_ro_pa_country_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_15": "gc pa country 15",
  "desc_rip_church_gc_pa_country_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_15": "ro pa local 15",
  "desc_rip_church_ro_pa_local_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_15": "gc east pa local 15",
  "desc_rip_church_gc_east_pa_local_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_15": "gc middle pa local 15",
  "desc_rip_church_gc_middle_pa_local_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_15": "gc rome pa local 15",
  "desc_rip_church_gc_rome_pa_local_15": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_16": "ro pa country 16",
  "desc_rip_church_ro_pa_country_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_16": "gc pa country 16",
  "desc_rip_church_gc_pa_country_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_16": "ro pa local 16",
  "desc_rip_church_ro_pa_local_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_16": "gc east pa local 16",
  "desc_rip_church_gc_east_pa_local_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_16": "gc middle pa local 16",
  "desc_rip_church_gc_middle_pa_local_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_16": "gc rome pa local 16",
  "desc_rip_church_gc_rome_pa_local_16": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_17": "ro pa country 17",
  "desc_rip_church_ro_pa_country_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_17": "gc pa country 17",
  "desc_rip_church_gc_pa_country_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_17": "ro pa local 17",
  "desc_rip_church_ro_pa_local_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_17": "gc east pa local 17",
  "desc_rip_church_gc_east_pa_local_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_17": "gc middle pa local 17",
  "desc_rip_church_gc_middle_pa_local_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_17": "gc rome pa local 17",
  "desc_rip_church_gc_rome_pa_local_17": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_18": "ro pa country 18",
  "desc_rip_church_ro_pa_country_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_18": "gc pa country 18",
  "desc_rip_church_gc_pa_country_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_18": "ro pa local 18",
  "desc_rip_church_ro_pa_local_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_18": "gc east pa local 18",
  "desc_rip_church_gc_east_pa_local_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_18": "gc middle pa local 18",
  "desc_rip_church_gc_middle_pa_local_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_18": "gc rome pa local 18",
  "desc_rip_church_gc_rome_pa_local_18": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_19": "ro pa country 19",
  "desc_rip_church_ro_pa_country_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_19": "gc pa country 19",
  "desc_rip_church_gc_pa_country_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_19": "ro pa local 19",
  "desc_rip_church_ro_pa_local_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_19": "gc east pa local 19",
  "desc_rip_church_gc_east_pa_local_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_19": "gc middle pa local 19",
  "desc_rip_church_gc_middle_pa_local_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_19": "gc rome pa local 19",
  "desc_rip_church_gc_rome_pa_local_19": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_country_20": "ro pa country 20",
  "desc_rip_church_ro_pa_country_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_pa_country_20": "gc pa country 20",
  "desc_rip_church_gc_pa_country_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_ro_pa_local_20": "ro pa local 20",
  "desc_rip_church_ro_pa_local_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_east_pa_local_20": "gc east pa local 20",
  "desc_rip_church_gc_east_pa_local_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_middle_pa_local_20": "gc middle pa local 20",
  "desc_rip_church_gc_middle_pa_local_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_gc_rome_pa_local_20": "gc rome pa local 20",
  "desc_rip_church_gc_rome_pa_local_20": "An adjustment belonging to the current church settlement; its effects end or change when its conditions cease to apply.",
  "rip_church_opinion_ro_recognized": "ro recognized",
  "rip_church_opinion_ro_unrecognized": "ro unrecognized",
  "rip_church_opinion_ro_schism": "ro schism",
  "rip_church_opinion_gc_catholic_east": "gc catholic east",
  "rip_church_opinion_gc_catholic_middle": "gc catholic middle",
  "rip_church_opinion_gc_catholic_rome": "gc catholic rome",
  "rip_church_opinion_gc_orthodox_east": "gc orthodox east",
  "rip_church_opinion_gc_orthodox_middle": "gc orthodox middle",
  "rip_church_opinion_gc_orthodox_rome": "gc orthodox rome",
  "rip_church_opinion_gc_ecumenical": "gc ecumenical",
  "rip_church_opinion_gc_ro_schism": "gc ro schism",
  "rip_church_opinion_propagation_conflict": "propagation conflict"
}

DATA.update({
 'rip_church_gc_native_privileges_button': 'Manage',
 'rip_church_gc_native_privileges_button_tt': 'Open church privileges. Opening this menu is free; only choosing a privilege spends resources.',
 'rip_church_ro_heading': 'The Muscovite Church',
 'rip_church_ro_policies_title': 'Church policies',
 'rip_church_ro_policies_title_tt': 'Use the button below an icon to activate or deactivate its policy. Active icons have a lit frame. Hover each button for its effects and payment conditions.',
 'rip_church_icon_war_button': 'Military',
 'rip_church_icon_mercy_button': 'Mercy',
 'rip_church_icon_building_button': 'Building',
 'rip_church_icon_mission_button': 'Mission',
 'rip_church_ro_status': '[Root.GetChurchROStatus]',
 'rip_church_ro_resources': 'Fervor: [Root.rip_church_fervor.GetValue] / 100   Icons: [Root.rip_church_icons.GetValue] / [Root.rip_church_capacity.GetValue]\\nMonthly Fervor: +[Root.rip_church_fervor_income.GetValue] / -[Root.rip_church_fervor_cost.GetValue]\\nFunded trade nodes: [Root.rip_church_nodes.GetValue]',
 'rip_church_ro_mission_cost': 'Each trade node: 2 Fervor now + 2 per month\\nRequires an active Apostolic Mission',
 'rip_church_nodes_button': 'Fund / close trade missions',
 'rip_church_nodes_button_tt': 'Requires a funded node to manage, or an eligible node you can afford. Each node costs 2 Fervor immediately and 2 each month, in addition to icon upkeep. No ducat fee. Opening the menu itself makes no payment. Activate Apostolic Mission first; a new node requires at least 12 Fervor, a merchant, 50% trade power, connected church infrastructure and an eligible target.',
 'rip_church_mission_network_desc': 'Muscovite Orthodox missionary network. A registered node costs 2 Fervor now and 2 per month, in addition to Apostolic Mission upkeep. No ducat fee. Requires a merchant, 50% trade power and connected controlled church infrastructure. Fund or close nodes from the church panel.',
 'rip_church_break_communion_title': 'Renounce the patriarchal settlement',
 'rip_church_break_communion_desc': 'Deliberate alternative history: abandon recognized communion and claim an independent universal church. This enables a second funded mission node, increases confessional conflict and imposes -1 diplomatic reputation. Earlier reconciliation payments are not refunded.',
 'rip_church_oppose_union_title': 'Change our policy toward the Union',
 'rip_church_oppose_union_desc': 'For 25 DIP, adopt or end state opposition to the Union. Opposition multiplies its conversion target weights in our provinces by 0.25 and adds a mutual -10 opinion with Greek Catholic countries. The policy can be changed once every five years.',
 'rip_church_withdraw_union_support_title': 'Withdraw royal support for the Union',
 'rip_church_withdraw_union_support_desc': 'End the Catholic crown\'s patronage. Any Centre of Union under our rule loses its eligible patron and ceases to operate. Earlier foundation and negotiation payments are not refunded.',
 'rip_church_opinion_union_opposition': 'State opposition to the Union',
 'rip_church_center_active': 'Our Centre of Union is active',
 'rip_church_center_suspended': 'Our Centre is suspended by occupation',
 'rip_church_center_elsewhere': 'The single Centre is held by another country',
 'rip_church_center_absent': '§RNo Centre of Union is established§!',
 'rip_church_icon_no_fuel': 'Blocked: at least 10 Fervor is required.',
 'rip_church_icon_no_slot': 'Blocked: authority currently provides no vacant icon slot.',
 'rip_church_icon_cooldown': 'Blocked: one year must pass after the previous activation of this icon.',
 'rip_church_icon_can_activate': 'Ready to activate.',
 'rip_church_icon_can_deactivate': 'Active: click to deactivate without a refund.',
 'rip_church_ro_high': 'Centralized church administration',
 'rip_church_ro_max': 'Intensive church centralization',
 'rip_church_ro_high_recognized': 'Recognized central administration',
 'rip_church_ro_max_recognized': 'Recognized intensive centralization',
 'rip_church_ro_schism': 'Universal claims in schism',
 'rip_church_reconciliation_unrest': 'Opposition to reconciliation',
 'rip_church_gc_infrastructure': 'Eastern church infrastructure',
 'rip_church_gc_coexistence': 'Agreement on coexistence',
 'rip_church_gc_legate': 'Papal legate',
 'rip_church_gc_dynastic': 'Papal support for legitimacy',
 'rip_church_gc_prestige': 'Papal recognition of standing',
 'rip_church_rite': 'Confessional autonomy',
 'rip_church_rite_favoured': 'Protected local tradition',
 'rip_church_rite_ecumenical': 'Ecumenical accommodation',
 'rip_church_rite_revoked': 'Revoked confessional autonomy',
 'rip_church_gc_roman_resistance': 'Resistance to Roman integration',
 'rip_church_conversion_resistance': 'Resistance to jurisdictional pressure',
 'rip_church_gc_local_see': 'Local Eastern Catholic see',
 'rip_church_conversion_pressure': 'Recent missionary pressure',
 'rip_church_opinion_ro_recognized': 'Recognized Orthodox communion',
 'rip_church_opinion_ro_unrecognized': 'Shared faith, disputed jurisdiction',
 'rip_church_opinion_ro_schism': 'Rival universal claims',
 'rip_church_opinion_gc_catholic_east': 'Communion with Eastern autonomy',
 'rip_church_opinion_gc_catholic_middle': 'Balanced communion with Rome',
 'rip_church_opinion_gc_catholic_rome': 'Close Roman communion',
 'rip_church_opinion_gc_orthodox_east': 'Respect for Eastern tradition',
 'rip_church_opinion_gc_orthodox_middle': 'Balanced confessional relations',
 'rip_church_opinion_gc_orthodox_rome': 'Rivalry over Roman integration',
 'rip_church_opinion_gc_ecumenical': 'Ecumenical settlement',
 'rip_church_opinion_gc_ro_schism': 'Conflicting ecclesiastical claims',
 'rip_church_opinion_propagation_conflict': 'Missionary intervention in our parishes',
})
for key in ('heading','status','resources','mission_cost'):
 DATA['rip_church_ro_'+key+'_tt']=DATA['rip_church_ro_'+key]
for icon in ('war','mercy','building','mission'):
    DATA['rip_church_icon_'+icon]=DATA['rip_church_icon_'+icon+'_button']
    DATA['desc_rip_church_icon_'+icon]=DATA['rip_church_icon_'+icon+'_button_tt']
    DATA['rip_church_icon_'+icon+'_button_tt']+='\\n[Root.GetChurchIcon'+icon.title()+'Access]'
DATA.update({
 'rip_church_gc_heading': 'Union of the Churches',
 'rip_church_gc_orientation': '[Root.GetChurchGCOrientation]',
 'rip_church_gc_resources': 'Communion balance: [Root.GetChurchBalanceValue]\\nPapal Standing: §Y[Root.rip_church_papal_standing.GetValue] / 100§!\\nMonthly rate: [Root.GetChurchStandingRate]',
 'rip_church_gc_parishes': 'Recognized parishes: §Y[Root.rip_church_recognized_parishes.GetValue]§!',
 'rip_church_gc_parish_count': '§Y[Root.rip_church_recognized_parishes.GetValue]§!',
 'rip_church_gc_parish_count_tt': 'Recognized parishes: [Root.rip_church_recognized_parishes.GetValue]',
 'rip_church_gc_balance_negative': '§R[Root.rip_church_communion.GetValue]§!',
 'rip_church_gc_balance_positive': '§Y[Root.rip_church_communion.GetValue]§!',
 'rip_church_gc_center_state': '[Root.GetChurchCenterStatus]',
 'rip_church_gc_policy_label': 'Communion policy',
 'rip_church_gc_policy_cost': '§Y25§!   |   §Y20§! balance',
 'rip_church_gc_privilege_state': 'Active privilege\\n§H[Root.GetChurchPrivilege]§!',
 'rip_church_gc_help': 'Start with Privileges. Local rites: select an owned province.\\nHover buttons for costs and conditions.',
 'rip_church_privileges_button': 'Privileges',
 'rip_church_center_button': 'Union seat',
 'rip_church_ecumenism_button': 'Ecumenism',
 'rip_church_standing_rate_zero': '§Y+0.00§!',
 'rip_church_standing_rate_east': '§G+0.10§!',
 'rip_church_standing_rate_middle': '§G+0.25§!',
 'rip_church_standing_rate_rome': '§G+0.50§!',
})
DATA.update({
 'rip_church_privileges_button': 'Synod',
 'rip_church_privileges_button_tt': 'Convene the local Greek Catholic synod. Choose Eastern infrastructure or a compact protecting local rites. These use Patriarch Authority and ducats, and share one ten-year privilege slot with papal petitions. Opening the menu is free.\\nCurrent institution: [Root.GetChurchLocalInstitution]',
 'rip_church_gc_native_privileges_button': 'Synod',
 'rip_church_gc_native_privileges_button_tt': 'Choose an institution of the Greek Catholic hierarchy. The picture shows the active local institution; these are not Orthodox icon bonuses. Opening the synod is free.\\nCurrent institution: [Root.GetChurchLocalInstitution]',
 'rip_church.6.t': 'The Local Synod',
 'rip_church.6.d': 'Our Eastern hierarchy can organize church infrastructure or agree protections for the rites of its parishes. These institutions spend Patriarch Authority and ducats. Only one church privilege may operate at a time, including petitions granted by Rome. Each lasts ten years.\\n\\nCurrent institution: [Root.GetChurchLocalInstitution]\\nPapal petitions are available in the Curia tab of the church panel.',
 'rip_church_gc_curia_heading': 'The Holy See and the Union',
 'rip_church_gc_curia_status': '[Root.GetChurchCuriaStatus]',
 'rip_church_gc_curia_good': 'In communion with Rome',
 'rip_church_gc_curia_cold': 'Roman support requires better relations',
 'rip_church_gc_curia_war': 'At war with the Papal State',
 'rip_church_gc_curia_absent': 'The Catholic Papal State is absent',
 'rip_church_gc_rome_resources': 'Papal opinion: [Root.GetChurchPapalOpinion]\\nStanding: §Y[Root.rip_church_papal_standing.GetValue] / 100§!\\nMonthly growth: [Root.GetChurchCuriaRate]',
 'rip_church_gc_opinion_value': '§Y[Root.rip_church_papal_opinion.GetValue]§!',
 'rip_church_gc_opinion_negative': '§R[Root.rip_church_papal_opinion.GetValue]§!',
 'rip_church_gc_opinion_absent': 'Unavailable',
 'rip_church_gc_rate_paused': 'Paused',
 'rip_church_gc_controller_label': 'Controller',
 'rip_church_gc_controller_name': '[rip_church_gc_controller.GetName]',
 'rip_church_gc_controller_none': 'No current controller',
 'rip_church_gc_pope_shield_tt': 'The Catholic Papal State. Click to open its country view. Opinion of us: [Root.GetChurchPapalOpinion]. The displayed opinion refreshes monthly and when opening the Curia tab; petition conditions always use current relations.',
 'rip_church_gc_controller_shield_tt': 'Curia controller for the current pontificate: [Root.GetChurchCuriaController]. This country won the last election; this is not a prediction of the next election. Click to open its country view.',
 'rip_church_gc_petitions_title': 'Papal petitions',
 'rip_church_gc_curia_privilege': 'Active church privilege\\n§H[Root.GetChurchPrivilege]§!',
 'rip_church_gc_donate_label': 'Donate',
 'rip_church_gc_donate_button_tt': 'Donate 100 ducats: gain 10 Papal Standing and +25 Papal opinion, decaying by 5 per year. Once every five years, including after a change of religion. Requires the Catholic Papal State, peace with it and at most 90 Standing. With Emperor, 50 ducats reach the Curia Treasury and 50 the Papal State; otherwise all 100 go to the Papal State. This grants no vote or invested papal influence.',
 'rip_church_gc_donation_cost': 'Donation to the Holy See\\n§Y100 ducats§!\\n§G+10 Standing§!; §G+25 Papal opinion§!',
 'rip_church_gc_donation_state': '[Root.GetChurchDonationState]',
 'rip_church_gc_donation_ready': 'Donation available',
 'rip_church_gc_donation_wait': 'Wait five years after the last donation',
 'rip_church_gc_donation_blocked': 'Donation requirements are not met',
 'rip_church_gc_donation_opinion': 'Donation from an Eastern Catholic church',
 'rip_church_gc_local_reserved': 'The common slot is reserved by a papal petition',
 'rip_church_gc_church_tax': 'Papal licence for church revenues',
 'desc_rip_church_gc_church_tax': 'A ten-year curial privilege: +10% national tax and -5% building cost.',
 'rip_church_gc_blessing': 'Papal blessing of the Union',
 'desc_rip_church_gc_blessing': 'A ten-year curial privilege: +1 yearly prestige and +5% army morale.',
 'rip_church_gc_usury': 'Curial settlement of debts',
 'desc_rip_church_gc_usury': 'A ten-year curial privilege: -0.25 interest, +0.05 yearly inflation reduction and -0.02 yearly corruption.',
 'rip_church_gc_holy_war': 'Papal support for the war effort',
 'desc_rip_church_gc_holy_war': 'A ten-year curial privilege: +7.5% manpower recovery and -2.5% land maintenance.',
 'rip_church_gc_saint': 'Recognition of a local saint',
 'desc_rip_church_gc_saint': 'The petition granted +1 stability immediately. It reserves the common church privilege slot for ten years and gives no additional ongoing bonus.',
 'rip_church_gc_monopoly': 'Papal commercial charter',
 'desc_rip_church_gc_monopoly': 'The petition granted +1 mercantilism immediately. It reserves the common church privilege slot for ten years and gives no additional ongoing bonus.',
})
for page in ('union','curia'):
 for tab in ('union','curia'):
  key=f'rip_church_gc_{tab}_tab_{page}'
  DATA[key]=tab.title()
  DATA[key+'_tt']=('Show communion policy, the local synod, parishes and the Centre of Union.' if tab=='union' else 'Show Papal relations, the current Curia controller, petitions and donations.')+' Switching tabs is free.'
for key,label,payload in (
 ('church_tax','Church tax','+10% national tax; -5% building cost.'),
 ('blessing','Blessing','+1 yearly prestige; +5% army morale.'),
 ('indulgence','Indulgence','+1 yearly legitimacy for a monarchy; otherwise +1 yearly prestige. Move balance 10 toward Rome.'),
 ('saint','Local saint','Gain +1 stability now. Requires stability below +3. The privilege slot remains reserved for ten years.'),
 ('usury','Usury','-0.25 interest; +0.05 yearly inflation reduction; -0.02 yearly corruption.'),
 ('holy_war','Holy war','+7.5% manpower recovery; -2.5% land maintenance. Requires an ongoing war.'),
 ('legate','Papal legate','+1 diplomatic reputation; +10% improve relations. Requires Roman orientation. Move balance 10 toward Rome.'),
 ('monopoly','Trade charter','Gain +1 mercantilism now. Requires mercantilism below 100. The privilege slot remains reserved for ten years.'),
):
 name='rip_church_gc_petition_'+key
 cost=60 if key=='saint' else 30
 tip=f'{payload}\\nCosts {cost} Papal Standing and 100 ducats. One common church privilege at a time, for ten years. Requires balanced or Roman orientation, the Catholic Papal State, peace with it and its opinion of us at least +50.'
 DATA[name+'_label']=label
 DATA[name+'_label_tt']=tip
 DATA[name+'_button_tt']='§Y'+label+'§!\\n'+tip
for key in ('curia_heading','curia_status','rome_resources','controller_label','petitions_title','curia_privilege','donate_label','donation_cost','donation_state'):
 DATA['rip_church_gc_'+key+'_tt']=DATA['rip_church_gc_'+key]
DATA['rip_church_gc_controller_label_tt']=DATA['rip_church_gc_controller_shield_tt']
DATA['rip_church_gc_rome_resources_tt']+='\\nOpinion refreshes monthly and on opening this tab. Papal Standing is separate from Catholic papal influence; it grants no electoral votes.'
for key in ('heading','orientation','resources','parishes','center_state','policy_label','policy_cost','privilege_state','help'):
 DATA['rip_church_gc_'+key+'_tt']=DATA['rip_church_gc_'+key]
DATA['rip_church_gc_resources_tt']+='\\nBalance runs from -100 (East) to +100 (Rome).\\nStanding grows only with Rome present, at peace with you, and at least +50 opinion.\\nPatriarch Authority is shown by the main religion window.'
DATA['rip_church_gc_policy_cost_tt']='§Y25 ADM§! to move communion balance by §Y20§!. Once every five years. Hover the policy buttons for their current requirements.'
DATA['rip_church_gc_donate_button_tt']+='\\n[Root.GetChurchDonationState]'
DATA['rip_church_gc_donation_cost_tt']=DATA['rip_church_gc_donate_button_tt']
for name in ('privileges','center','ecumenism'):
 DATA['rip_church_'+name+'_button_tt']='§Y'+DATA['rip_church_'+name+'_button']+'§!\\n'+DATA['rip_church_'+name+'_button_tt']
 DATA['rip_church_'+name+'_button_label']=DATA['rip_church_'+name+'_button']
 DATA['rip_church_'+name+'_button_label_tt']=DATA['rip_church_'+name+'_button_tt']
DATA['rip_church_nodes.1.d']+=' Requires Cradle of Civilization; without that DLC, no node can be funded.'
DATA['rip_church_center_button_tt']+=' Occupation suspends the centre and reserves the world slot. Liberation restarts native conversion; its previous in-flight progress may be lost.'
for key in list(DATA):
    match=re.fullmatch(r'rip_church_(ro|gc)(?:_(east|middle|rome))?_pa_(country|local)_(\d+)',key)
    if match:
        DATA[key]='Church authority adjustment: '+str(int(match[4])*5)+'%'
        DATA['desc_'+key]='Offsets the inherited Orthodox authority bonus for this confession. Recalculated in five-point authority bands; the native Orthodox faith is unchanged.'

DATA.update({
 'rip_church_gc_course_range':'East -100     |     Balanced -40 ... +40     |     Rome +100',
 'rip_church_gc_course_range_tt':'The current orientation controls access to local and Roman privileges. Monthly Standing is +0.10 / +0.25 / +0.50 only while a Catholic PAP exists, is at peace with us and has at least +50 opinion of us.',
 'rip_church_gc_privilege_state':'[Root.GetChurchSlotState]\\n§H[Root.GetChurchPrivilege]§!',
 'rip_church_gc_curia_privilege':'[Root.GetChurchSlotState]\\n§H[Root.GetChurchPrivilege]§!',
 'rip_church_gui_parishes_heading':'Parishes and the Centre of Union',
 'rip_church_gui_coexistence':'[Root.GetChurchCoexistenceState]',
 'rip_church_gui_coexistence_active':'§GCompact of coexistence active§!',
 'rip_church_gui_coexistence_ecumenical':'§GEcumenical settlement recognized§!',
 'rip_church_gui_coexistence_local':'Local rites retain their own agreements',
 'rip_church_gui_parish_counts':'Recognized Eastern parishes: §Y[Root.rip_church_gui_eastern_parishes.GetValue]§!\\nRecognized Latin parishes: §Y[Root.rip_church_gui_latin_parishes.GetValue]§!\\nLatin consent to conversion: §Y[Root.rip_church_gui_latin_consents.GetValue]§!',
 'rip_church_gui_parish_counts_tt':'Counts only our provinces; refreshed on opening this tab and monthly. Recognition preserves the province religion and excludes it from Union conversion. Latin consent is a separate paid permission for gradual conversion. Select an owned province to recognize, revoke or grant consent.',
 'rip_church_gui_network_title':'One shared Centre of Union',
 'rip_church_gui_network_scope':'[Root.GetChurchNetworkScope]',
 'rip_church_gui_network_normal':'Network access: §Yrings 0-2§!\\nLatin consent: §Yring 0 only§!',
 'rip_church_gui_network_extended':'Network access: §Yrings 0-4§!\\nLatin consent: §Yextended network§!',
 'rip_church_gui_network_none':'No active network\\nEstablish or restore the shared Union seat',
 'rip_church_gui_network_scope_tt':'Rings are connected areas, bridged by existing Greek Catholic parishes. The native centre also checks its 150 distance limit. Nearby Eastern targets have higher weights; Latin targets need explicit consent and have lower base priority. Recognized rites are excluded. Occupation suspends the centre while retaining the one world slot.',
 'rip_church_gui_found_center':'Establish Union seat',
 'rip_church_gui_found_center_tt':'Pay §Y100 ADM and one year of income§! to establish the sole Centre of Union. Requires peace, stability +1, an eligible controlled Greek Catholic core with development 10 and a temple or cathedral. An occupied centre still reserves the world slot. Founding cooldown: twenty years.',
 'rip_church_gui_slot_state':'[Root.GetChurchSlotState]',
 'rip_church_gui_slot_free':'Shared privilege: §G0 / 1§!',
 'rip_church_gui_slot_used':'Shared privilege: §Y1 / 1§!',
 'rip_church_gui_slot_patron':'Catholic patron: local GC slot unavailable',
 'rip_church_gui_slot_state_tt':'The local synod and all eight Roman petitions share one ten-year slot. A saint or trade charter gives an immediate reward but reserves the slot for ten years. Opening menus never pays for a privilege.',
 'rip_church_gui_active_institution':'Active institution\\n§H[Root.GetChurchPrivilege]§!',
 'rip_church_gui_synod':'Local synod',
 'rip_church_gui_ecumenism':'Ecumenism',
 'rip_church_gui_paths_heading':'Paths to the Union',
 'rip_church_gui_path_status':'[Root.GetChurchUnionPathState]',
 'rip_church_gui_path_orthodox':'Orthodox acceptance of the Union',
 'rip_church_gui_path_catholic':'Catholic patronage of Eastern parishes',
 'rip_church_gui_path_patron':'§GCatholic patron of the Union§!',
 'rip_church_gui_path_identity':'[Root.GetChurchUnionPathIdentity]',
 'rip_church_gui_identity_orthodox':'State acceptance changes our confession.\\nExisting parish rites require separate agreements.',
 'rip_church_gui_identity_catholic':'Patronage preserves our Catholic confession.\\nAn Eastern founding parish enters the Union.',
 'rip_church_gui_paths_title':'Negotiations and settlement',
 'rip_church_gui_florence':'Florentine negotiations',
 'rip_church_gui_florence_tt':'Begin the early route in 1444-1501: §Y200 ADM, 100 DIP and one year of income§!. Requires peace, stability +2, PAP opinion +100 and an eligible Orthodox core parish. After five years, peace, stability and relations are checked again. Orthodox acceptance changes state faith; Catholic completion grants patronage and one founding parish. One attempt.',
 'rip_church_gui_adopt':'Accept the Union',
 'rip_church_gui_adopt_tt':'Conclude the later Orthodox state route from 1596, paying §Y100 ADM and 100 DIP§!. Uses exactly the current national decision gates: regional state, enabled faith, peace, stability, Catholic contact or union pressure, and qualifying Orthodox parishes. Catholic countries cannot use this action.',
 'rip_church_gui_sponsor':'Sponsor the Union',
 'rip_church_gui_sponsor_tt':'From 1596, pay §Y100 ADM, 100 DIP and one year of income§! to support the Union while remaining Catholic. Requires peace, stability +1, PAP without war, and a qualifying Orthodox core parish. One eligible parish becomes Greek Catholic. This does not create a centre for free.',
 'rip_church_gui_path_progress':'[Root.GetChurchFlorenceProgress]',
 'rip_church_gui_florence_wait':'Florentine negotiations: five-year term underway',
 'rip_church_gui_florence_due':'Term complete: settlement conditions must hold',
 'rip_church_gui_florence_done':'§GFlorentine settlement concluded§!',
 'rip_church_gui_florence_none':'No Florentine negotiations in progress',
 'rip_church_gui_patron_network':'Parishes and Union seat',
 'rip_church_gui_patron_network_tt':'Open the parish and centre panel. Catholic patrons can establish the centre and grant Latin consent; the Greek Catholic synod and petitions require that state confession.',
 'rip_church_gui_province_network':'Rite: [Root.GetChurchRiteFamily]\\nNetwork: [Root.GetChurchProvinceRing]\\n[Root.GetChurchProvinceUnionAccess]',
 'rip_church_gui_rite_eastern':'Eastern', 'rip_church_gui_rite_latin':'Latin',
 'rip_church_gui_ring_outside':'outside the connected rings',
 'rip_church_gui_protected':'§GRecognized rite: protected from Union conversion§!',
 'rip_church_gui_access_yes':'Network permits conversion; native range applies',
 'rip_church_gui_access_no':'§YUnion conversion conditions are not met§!',
 'rip_church_gui_province_network_tt':'Recognition keeps the local confession. Latin consent permits gradual conversion and is not recognition. Rings describe the game network, not historical jurisdiction. Native distance and conversion rules still apply. Refreshes with monthly network maintenance.',
})
DATA['rip_church_center_button_tt']='§YCentre and parishes§!\\nOpen the network panel, review recognized rites and Latin consent, or establish the sole Centre of Union.'
DATA['rip_church_gui_synod_tt']=DATA['rip_church_privileges_button_tt']
DATA['rip_church_gui_ecumenism_tt']=DATA['rip_church_ecumenism_button_tt']+' The 60 Standing requirement is a threshold; this settlement does not spend it.'
for i in range(5): DATA['rip_church_gui_ring_'+str(i)]='ring '+str(i)
for page in ('union','curia','parishes'):
 for tab in ('union','curia','parishes'):
  key=f'rip_church_gc_{tab}_tab_{page}'
  DATA[key]=tab.title()
  DATA[key+'_tt']={'union':'Communion policy; Catholic patrons return to their Union paths.', 'curia':'Papal relations and paid petitions for a Greek Catholic state.', 'parishes':'Recognized Eastern and Latin rites, consent, centre network and the shared privilege.'}[tab]
for key in list(DATA):
 if key.startswith('rip_church_gui_') and not key.endswith('_tt'): DATA.setdefault(key+'_tt',DATA[key])
for key in ('rip_church_gc_privilege_state_tt','rip_church_gc_curia_privilege_tt'): DATA[key]=DATA['rip_church_gui_slot_state_tt']

# The September simplification removed the global conversion centre, numerical
# Communion/Standing resources, Curia petitions, donations and their GUI.
retired_fragments=(
 'communion','standing','curia','petition','donat','center','centre','network',
 'union_ring','latin_consent','course_range','policy_cost','policy_label',
 'east_button','rome_button','papal_support','legate','dynastic','gc_prestige',
 'church_tax','blessing','usury','holy_war','saint','monopoly','controller_shield',
 'pope_shield','province_ring','province_union_access','patron_network')
for key in list(DATA):
 if any(fragment in key.lower() for fragment in retired_fragments): del DATA[key]
DATA.update({
 'rip_church.6.d':'The Eastern hierarchy may organize church infrastructure or conclude a compact protecting recognized local rites. Both are local synodal institutions, spend Patriarch Authority and ducats, and last ten years. Only one may operate at a time.',
 'rip_church_gc_heading':'THE UNION OF THE CHURCHES',
 'rip_church_gc_resources':'Eastern hierarchy in communion with Rome\\nLocal rites are managed parish by parish',
 'rip_church_gc_resources_tt':'The main religion window shows Patriarch Authority. This panel has no Communion Balance or accumulated Papal Standing resource.',
 'rip_church_gui_parishes_title':'Recognized parishes',
 'rip_church_gui_parish_counts':'Recognized Eastern parishes: §Y[Root.rip_church_gui_eastern_parishes.GetValue]§!\\nRecognized Latin parishes: §Y[Root.rip_church_gui_latin_parishes.GetValue]§!',
 'rip_church_gui_parish_counts_tt':'Counts only our provinces and refreshes monthly. Recognition preserves the province religion and grants local autonomy. Select an owned province to recognize or revoke its rite.',
 'rip_church_gui_institutions_title':'Local synodal institutions',
 'rip_church_gui_slot_state':'[Root.GetChurchSlotState]',
 'rip_church_gui_slot_free':'Synodal institution: §G0 / 1§!',
 'rip_church_gui_slot_used':'Synodal institution: §Y1 / 1§!',
 'rip_church_gui_slot_state_tt':'Infrastructure and coexistence share one ten-year local synodal slot. Opening the synod is free.',
 'rip_church_gui_active_institution':'Active institution\\n§H[Root.GetChurchPrivilege]§!',
 'rip_church_gui_synod':'Local synod',
 'rip_church_gui_synod_tt':'Choose Eastern infrastructure or a compact protecting recognized local rites. These use Patriarch Authority and ducats and last ten years.',
 'rip_church_gui_ecumenism':'Ecumenism',
 'rip_church_gui_ecumenism_tt':'A long-term settlement requiring twenty years of union, stability +2, peace, recognized Orthodox and Latin parishes, and an Orthodox ally with opinion +100.',
 'rip_church_gui_local_note':'No automatic centre converts neighbouring provinces.',
 'rip_church_gui_patron_state':'[Root.GetChurchPatronState]',
 'rip_church_gui_patron_active':'§GCatholic patronage is established§!\\nThe state remains Catholic; parish changes require explicit events or decisions.',
 'rip_church_gui_patron_inactive':'Patronage has not been established',
 'rip_church_gui_sponsor_tt':'From 1596, pay §Y100 ADM, 100 DIP and one year of income§! to support the Union while remaining Catholic. Requires peace, stability +1, PAP without war, and a qualifying Orthodox core parish. One eligible parish becomes Greek Catholic.',
 'rip_church_rite_help':'Recognition costs §Y1 ADM per current development§!, preserves the local confession, removes its religious-unity penalty and reduces direct taxation and recruitment. It lasts at least ten years. Revocation causes ten years of unrest.',
 'rip_church_rite_help_tt':'Recognition is local autonomy, not automatic conversion. Orthodox, Muscovite Orthodox and Latin parishes are counted separately in the country panel.',
})
for key in list(DATA):
 if key.startswith('rip_church_gui_') and not key.endswith('_tt'): DATA.setdefault(key+'_tt',DATA[key])

ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args()
# Generated variable/modifier definitions may add display-only compensation IDs.
for p in (ROOT/'common/event_modifiers').glob('RIP_church*.txt'):
    for key in re.findall(r'(?m)^(\w+)\s*=\s*\{',p.read_text(encoding='utf-8-sig')):
        DATA.setdefault(key,key.removeprefix('rip_church_').replace('_',' ').title())
        DATA.setdefault('desc_'+key,'Part of the current ecclesiastical settlement. Numerical adjustments follow authority and orientation.')
def defined(name,rows):
    result=f'defined_text = {{\n name = {name}\n'
    for trigger,key in rows:
        result+=f' text = {{ trigger = {{ {trigger} }} localisation_key = {key} }}\n'
    return result+'}\n'
custom=defined('GetChurchROStatus',[
 ('has_country_flag = rip_church_reconciliation_pending','rip_church_ro_reconciling'),
 ('has_country_flag = rip_church_ro_schismatic','rip_church_ro_schismatic'),
 ('rip_church_ro_recognized = yes','rip_church_ro_recognized'),
 ('has_country_flag = rip_church_ro_provisional','rip_church_ro_provisional'),
 ('always = yes','rip_church_ro_unrecognized')])
custom+=defined('GetChurchPrivilege',[(f'has_country_modifier = rip_church_gc_{key}',f'rip_church_gc_{key}') for key in ('infrastructure','coexistence')]+[('always = yes','rip_church_none')])
custom+=defined('GetChurchLocalInstitution',[
 ('has_country_modifier = rip_church_gc_infrastructure','rip_church_gc_infrastructure'),
 ('has_country_modifier = rip_church_gc_coexistence','rip_church_gc_coexistence'),
 ('always = yes','rip_church_none')])
custom+=defined('GetChurchRiteStatus',[
 ('has_province_flag = rip_church_rite_recognized','rip_church_rite_recognized'),
 ('always = yes','rip_church_rite_unrecognized')])
for key in ('war','mercy','building','mission'):
    custom+=defined('GetChurchIcon'+key.title(),[(f'has_country_flag = rip_church_icon_{key}','rip_church_active'),('always = yes','rip_church_inactive')])
    custom+=defined('GetChurchIcon'+key.title()+'Access',[
        (f'has_country_flag = rip_church_icon_{key}','rip_church_icon_can_deactivate'),
        ('NOT = { check_variable = { which = rip_church_fervor value = 10 } }','rip_church_icon_no_fuel'),
        ('NOT = { rip_church_ro_slot_available = yes }','rip_church_icon_no_slot'),
        (f'has_country_flag = rip_church_icon_{key}_used NOT = {{ had_country_flag = {{ flag = rip_church_icon_{key}_used days = 365 }} }}','rip_church_icon_cooldown'),
        ('always = yes','rip_church_icon_can_activate')])
custom+=defined('GetChurchSlotState',[
 ('rip_church_gc_has_privilege = yes','rip_church_gui_slot_used'),('always = yes','rip_church_gui_slot_free')])
custom+=defined('GetChurchCoexistenceState',[
 ('has_country_flag = rip_church_ecumenical','rip_church_gui_coexistence_ecumenical'),
 ('has_country_modifier = rip_church_gc_coexistence','rip_church_gui_coexistence_active'),('always = yes','rip_church_gui_coexistence_local')])
custom+=defined('GetChurchUnionPathState',[
 ('religion = orthodox','rip_church_gui_path_orthodox'),('has_country_flag = rip_church_supports_union','rip_church_gui_path_patron'),('always = yes','rip_church_gui_path_catholic')])
custom+=defined('GetChurchUnionPathIdentity',[
 ('religion = orthodox','rip_church_gui_identity_orthodox'),('always = yes','rip_church_gui_identity_catholic')])
custom+=defined('GetChurchFlorenceProgress',[
 ('has_country_flag = rip_church_florentine_union','rip_church_gui_florence_done'),
 ('has_country_flag = rip_church_florence_pending had_country_flag = { flag = rip_church_florence_pending days = 1825 }','rip_church_gui_florence_due'),
 ('has_country_flag = rip_church_florence_pending','rip_church_gui_florence_wait'),('always = yes','rip_church_gui_florence_none')])
custom+=defined('GetChurchRiteFamily',[('religion = catholic','rip_church_gui_rite_latin'),('always = yes','rip_church_gui_rite_eastern')])
custom+=defined('GetChurchPatronState',[
 ('has_country_flag = rip_church_supports_union','rip_church_gui_patron_active'),
 ('always = yes','rip_church_gui_patron_inactive')])
outputs={'customizable_localization/rip_church_redesign.txt':custom}
for lang in ('english','french','german','spanish'):
    outputs[f'localisation/replace/zzzz_RIP_church_redesign_l_{lang}.yml']='\ufeffl_'+lang+':\n'+''.join(f' {k}:0 "{v.replace(chr(34),chr(39))}"\n' for k,v in sorted(DATA.items()))
stale=[]
for path,text in outputs.items():
    p=ROOT/path
    if not p.exists() or p.read_text(encoding='utf-8')!=text:
        stale.append(path)
        if not args.check:
            p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8',newline='\n')
print(('STALE' if args.check and stale else 'GENERATED')+f': {len(DATA)} keys; {len(stale)} files')
if args.check and stale: raise SystemExit(1)
