"""Source copy for the Muscovite historical forks; emitted in all supported UI languages."""
COPY = {
 'russian_orthodox.1.t': 'The Election of a Metropolitan',
 'russian_orthodox.1.d': 'Our bishops propose electing their metropolitan without awaiting Constantinople. This establishes a local autocephalous jurisdiction within Orthodoxy. Our state and provinces remain Orthodox. A separate Muscovite confession can emerge only through a deliberate later schism or the Raskol.',
 'russian_orthodox.1.a': 'Elect our metropolitan within Orthodoxy',
 'russian_orthodox.1.b': 'Continue to seek approval from Constantinople',
 'russian_orthodox.2.d': 'Patriarchal dignity offers our church a recognized place among the Eastern patriarchates. Accepting recognition preserves Orthodox communion and our present faith; conciliar confirmation follows from 1593. Refusing their authority is a deliberate alternative-history schism: it establishes a separate Muscovite confession and removes protection for Orthodox parishes.',
 'russian_orthodox.2.a': 'Accept patriarchal dignity in Orthodox communion',
 'russian_orthodox.2.b': 'Defer the settlement for now',
 'rip_church_recognition_refuse': 'Break communion and establish a separate confession',
 'convert_to_russian_orthodox_decision_title': 'Elect an Independent Metropolitan',
 'convert_to_russian_orthodox_decision_desc': 'Establish our local Orthodox hierarchy. Costs 150 ADM and 100 DIP. The state and all provinces remain Orthodox. This opens later patriarchal and confessional choices, rather than converting the country in the fifteenth century.',
 'rip_ro_renounce_communion_title': 'Renounce Eastern Orthodox Communion',
 'rip_ro_renounce_communion_desc': 'Deliberately proclaim a separate Muscovite confession. Costs 100 DIP and 1 stability. Our Orthodox core capital follows the hierarchy once; other provinces keep their faith. Orthodox parish protections end and our relations with the other Eastern churches deteriorate. This is an alternative-history choice, not the automatic consequence of autocephaly.',
 'russian_orthodox.14.d': 'Our established patriarchate has received recognition within Orthodox communion. Its traditional title can now be adopted at home. This confers neither jurisdiction over every Orthodox country nor a new universal patriarchate.',
 'russian_orthodox.14.a': 'Adopt the patriarchal title',
 'russian_orthodox.6.d': 'The correction of the service books has reached a formal council. Condemning the old rites will create the Raskol and a separate Muscovite confession in game terms, while preserving communion with the other Eastern churches unless we have deliberately broken it. Repression weakens protection for Orthodox parishes; accepting both rites avoids the confessional separation and its disaster at the price of weaker uniformity.',
 'russian_orthodox.6.a': 'Enforce the council and suppress the old rites',
 'russian_orthodox.6.b': 'Confirm the new books but tolerate private old rites',
 'russian_orthodox.6.c': 'Accept both rites and prevent the rupture',
 'rip_ro_history.1.t': 'The Correction of the Service Books',
 'rip_ro_history.1.d': 'The patriarch proposes correcting the books against contemporary Greek practice. Implementing the revision begins a dispute over ritual authority; it does not yet create a new confession. From 1666 a council will decide whether to condemn the old rites. Recognizing both practices now avoids that rupture, at a continuing cost to uniform missionary policy and patriarchal authority.',
 'rip_ro_history.1.a': 'Correct the books; leave judgment to a later council',
 'rip_ro_history.1.b': 'Protect both ritual traditions',
 'rip_ro_history.2.t': 'The Vacant Patriarchal Throne',
 'rip_ro_history.2.d': 'The succession to the patriarchal throne confronts the crown with a choice. A locum tenens would administer the church while the ruler delays a new election, weakening patriarchal authority and clerical loyalty. Electing a new patriarch preserves the institution and clerical influence, at the expense of crown revenues.',
 'rip_ro_history.2.a': 'Delay the election and appoint a locum tenens',
 'rip_ro_history.2.b': 'Elect a patriarch and preserve the office',
 'rip_ro_history.3.t': 'The Ecclesiastical Regulation',
 'rip_ro_history.3.d': 'A governing synod under the crown can replace the vacant patriarchal office. It improves tax administration and reduces stability costs, but diminishes autonomous patriarchal authority and clerical loyalty. Alternatively, we can restore the patriarchal succession. This institutional choice does not change our religion or sever communion with the Eastern churches.',
 'rip_ro_history.3.a': 'Establish the Governing Synod under the crown',
 'rip_ro_history.3.b': 'Restore the patriarchal succession',
 'rip_ro_shared_communion': 'Orthodox Communion Preserved',
 'desc_rip_ro_shared_communion': 'This Orthodox parish shares communion with our hierarchy. Local heretic tolerance +5; its religious-unity weight is removed. EU4 retains the generic heretic label for different religions, but these local protections apply only to Orthodox parishes. Repression reduces them; a deliberate schism removes them.',
 'rip_ro_restricted_communion': 'Orthodox Communion under Restrictions',
 'desc_rip_ro_restricted_communion': 'The state restricts religious practice without renouncing Eastern communion. Orthodox parishes retain +3 local heretic tolerance and half their religious-unity weight is removed. Protection returns when the coercive policy expires, or disappears upon a deliberate schism.',
 'rip_ro_ritual_compromise': 'Two Ritual Traditions',
 'desc_rip_ro_ritual_compromise': 'Both old and revised rites are permitted. The Raskol disaster and its recurring Old Believer backlash are prevented. Missionary strength -0.5%; yearly patriarchal authority -0.5 percentage points. This is a counterfactual settlement.',
 'rip_ro_patriarchal_vacancy': 'Patriarchal Interregnum',
 'desc_rip_ro_patriarchal_vacancy': 'A locum tenens administers the church while the crown delays the patriarchal election. From 1721 the institutional settlement can establish a synod or restore the succession.',
 'rip_ro_synodal_government': 'The Governing Synod',
 'desc_rip_ro_synodal_government': 'A governing synod answers to the crown. Tax +5%, stability cost -5%, yearly patriarchal authority -0.5 percentage points, clergy loyalty equilibrium -5%. Communion is unchanged.',
 'rip_ro_preserved_patriarchate': 'Preserved Patriarchal Succession',
 'desc_rip_ro_preserved_patriarchate': 'An independent patriarchal office retains clerical influence. Yearly patriarchal authority +0.5 percentage points, clergy loyalty equilibrium +5%, tax -5%. Communion is unchanged.',
 'russian_orthodox.4.t': 'Imperial Administrative Assimilation',
 'russian_orthodox.4.d': 'Our eighteenth-century administration seeks greater linguistic and institutional uniformity. Coercion will provoke provincial resistance. We may instead support gradual integration or retain local arrangements. The policy is a gameplay abstraction, not an institution of the medieval metropolitanate.',
 'russian_orthodox.4.a': 'Impose administrative and linguistic uniformity',
 'forced_russification': 'Coercive Administrative Assimilation',
 'russification_campaign_decision_title': 'Impose Administrative Assimilation',
 'russification_campaign_decision_desc': 'Available from 1700. Spend 100 ADM and 50 MIL on a coercive twenty-year administrative policy. Local resistance and missionary disputes may follow; cultures do not change instantly.',
 'russian_orthodox.5.t': 'Confessional Courts after the Council',
 'russian_orthodox.5.d': 'After the council, church courts and secular officers can enforce approved religious practice. Strong coercion threatens Orthodox parish guarantees and may provoke resistance. These confessional courts are not a copy of the Roman Inquisition.',
 'russian_orthodox.5.a': 'Authorize coercive confessional courts',
 'russian_orthodox.5.b': 'Permit limited religious prosecutions',
 'russian_orthodox.5.c': 'Preserve religious accommodation',
 'orthodox_inquisition': 'Coercive Confessional Courts',
 'establish_orthodox_inquisition_decision_title': 'Authorize Confessional Courts',
 'establish_orthodox_inquisition_decision_desc': 'Available from 1667. Spend 75 ADM and 15 percentage points of patriarchal authority. Coercive enforcement lasts twenty years, weakens protection for Orthodox parishes and can provoke religious backlash.',
 'rip_church_ro_unrecognized': 'Muscovite confession in Eastern communion',
 'rip_church_ro_restricted_status': 'Orthodox communion with parish restrictions',
 'rip_church_ro_synodal_status': 'Governing Synod in Orthodox communion',
 'rip_church_ro_policies_title_tt': 'Click an icon to activate or deactivate its policy. The lit frame marks an active policy; the check or cross shows availability. Benefits and costs are shown below; hover for complete conditions.',
}
