# Crash Information
AppName: EUIV 
AppVersion: EU4 v1.37.5.0 Inca 
SCMBranch: HEAD 
SCMCommit: 835bfdf8ca24c291a1b3f1b5bc72d47e7df1ae18 
SCMTimeStamp: "2024-10-03 10:50:26 +0200" 
DateTime: "2026-09-29 17:22:05" 
BuildType: Release 
Platform: Windows 
Architecture: 64-bit 
OperatingSystem: Windows 10 x86_64 
SystemLanguage: ru 
CPUModel: AMD Ryzen 7 5800X3D 8-Core Processor            
CPUSpeed: 0 
CPUPhysicalCores: 8 
CPULogicalCores: 16 
SystemMemory: 32693 
LaunchArguments: --auto_run="" --debug_mode --seed="" --start_tag="" --userdir="" 

# Application Specific Data 
Mods: mod/RIP.mod,mod/rip_pr2_harness.mod 
